"use client";
import Link from "next/link";
import { upload } from "@vercel/blob/client";
import { useParams } from "next/navigation";
import { useState } from "react";
import { ArrowLeft, Banknote, CheckCircle2, CreditCard, Loader2, ShieldCheck, UploadCloud } from "lucide-react";
import { SiteHeader } from "../../../../components/SiteShell";

type Bank={id:string;bankName:string;accountName:string;accountNumber:string;currency:string;instructions?:string};
type Invoice={reference:string;amount:number;currency:string;status:string;clientName:string};
export default function PaymentPage(){
 const params=useParams<{reference:string}>();const reference=decodeURIComponent(params.reference);const[email,setEmail]=useState("");const[verified,setVerified]=useState(false);const[invoice,setInvoice]=useState<Invoice|null>(null);const[accounts,setAccounts]=useState<Bank[]>([]);const[notice,setNotice]=useState("");const[loading,setLoading]=useState(false);
 async function verify(){setLoading(true);setNotice("");const r=await fetch(`/api/payments/pay/${encodeURIComponent(reference)}?email=${encodeURIComponent(email)}`);const d=await r.json();if(r.ok){setInvoice(d.invoice||{reference,amount:850000,currency:"NGN",status:"sent",clientName:"Duches Private Client"});setAccounts(d.accounts||[]);setVerified(true)}else setNotice(d.error||"Unable to verify invoice.");setLoading(false)}
 async function provider(name:string){setLoading(true);const r=await fetch(`/api/payments/pay/${encodeURIComponent(reference)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,provider:name})});const d=await r.json();if(d.checkoutUrl)window.location.href=d.checkoutUrl;else{if(d.accounts)setAccounts(d.accounts);setNotice(d.status==="provider_not_connected"?"This payment provider will activate once Duches connects its live account.":d.message||d.status||"Payment option ready.")}setLoading(false)}
 async function submitTransfer(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);const form=new FormData(e.currentTarget);let proofUrl="";const file=form.get("proof") as File;if(file?.size){const blob=await upload(`receipts/${reference}/${file.name}`,file,{access:"public",handleUploadUrl:"/api/payments/bank-transfer/proof",clientPayload:JSON.stringify({invoiceReference:reference,email})});proofUrl=blob.url}const payload={invoiceReference:reference,clientName:invoice?.clientName||String(form.get("clientName")),senderBank:form.get("senderBank"),senderAccountName:form.get("senderAccountName"),transferReference:form.get("transferReference"),amount:Number(invoice?.amount),currency:invoice?.currency,proofUrl,note:form.get("note")};const r=await fetch('/api/payments/bank-transfer/submit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();setNotice(r.ok?"Transfer submitted. Duches will verify receipt before confirming your booking.":d.error||"Unable to submit transfer.");setLoading(false)}
 return <main><SiteHeader/><section className="payment-shell"><Link className="ops-back" href="/client"><ArrowLeft size={15}/> Private client portal</Link><div className="payment-card"><p className="eyebrow dark-eye">Secure payment</p><h1>Invoice {reference}</h1><p className="payment-lead">Verify your invoice, choose a payment method and complete your transaction. Direct bank transfers remain pending until Duches confirms receipt.</p>{!verified?<div className="payment-verify"><label>Email on invoice<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><button onClick={verify} disabled={loading||!email}>{loading?<Loader2 className="spin" size={16}/>:<ShieldCheck size={16}/>} Verify invoice</button></div>:<><div className="payment-summary"><div><span>Client</span><strong>{invoice?.clientName}</strong></div><div><span>Amount due</span><strong>{invoice?.currency} {Number(invoice?.amount||0).toLocaleString()}</strong></div><div><span>Status</span><strong>{invoice?.status}</strong></div></div><div className="payment-methods"><button onClick={()=>provider('flutterwave')}><CreditCard size={20}/><strong>Flutterwave</strong><span>Card · bank transfer · USSD</span></button><button onClick={()=>provider('paystack')}><CreditCard size={20}/><strong>Paystack</strong><span>Local checkout</span></button><button onClick={()=>provider('stripe')}><CreditCard size={20}/><strong>Stripe</strong><span>International cards</span></button><button onClick={()=>provider('bank_transfer')}><Banknote size={20}/><strong>Direct bank transfer</strong><span>Owner verified</span></button></div>{accounts.length>0&&<section className="bank-payment"><div className="bank-heading"><Banknote size={22}/><div><h2>Transfer to Duches</h2><p>Use the invoice reference as your narration where possible.</p></div></div>{accounts.map(a=><article className="bank-account" key={a.id}><span>{a.bankName}</span><strong>{a.accountNumber}</strong><p>{a.accountName} · {a.currency}</p><small>{a.instructions}</small></article>)}<form onSubmit={submitTransfer} className="transfer-form"><label>Your bank<input name="senderBank" required/></label><label>Sender account name<input name="senderAccountName" required/></label><label>Transfer reference<input name="transferReference"/></label><label className="full">Upload transfer receipt<input name="proof" type="file" accept="image/jpeg,image/png,image/webp,application/pdf"/><small><UploadCloud size={14}/> JPG, PNG, WEBP or PDF · max 8 MB</small></label><label className="full">Note<textarea name="note" placeholder="Optional payment note"/></label><button className="full" disabled={loading}>{loading?<Loader2 className="spin" size={16}/>:<CheckCircle2 size={16}/>} Submit for verification</button></form></section>}</>}{notice&&<p className="payment-notice">{notice}</p>}</div></section></main>}
