import Link from "next/link";
import { Activity, BookOpen, Clock3, Dumbbell, HeartPulse, Play, ScanLine } from "lucide-react";
import { CTA, Eyebrow, Footer, PublicNav } from "../ui";

const guides=[
["CHEST + TRICEPS","Build muscle","Intermediate","48 min","https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=1200&q=82"],
["LOWER BODY POWER","Strength","Advanced","55 min","https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=1200&q=82"],
["FAT-LOSS ENGINE","Conditioning","All levels","32 min","https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1200&q=82"],
["MOBILITY RESET","Recovery","All levels","18 min","https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1200&q=82"],
["HOME DUMBBELL LAB","Build muscle","Beginner","36 min","https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1200&q=82"],
["RUN STRONG","Endurance","Intermediate","40 min","https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=1200&q=82"]
];

export default function GuidesPage(){return <><PublicNav/><main className="fo-guides-page">
<section className="fo-guides-hero"><div><Eyebrow>Fitness Option Training Library</Eyebrow><h1 className="fo-display">KNOW WHAT<br/>TO DO. <em>KNOW WHY.</em></h1><p className="fo-copy">Exercise demonstrations, technique cues, muscle maps, progressions and complete sessions give members a coach-guided reference every time they train.</p><div className="fo-social-proof"><span><BookOpen size={13}/> 86 demo guides</span><span><Play size={13}/> Video-ready</span><span><ScanLine size={13}/> Form Check linked</span></div></div><div className="fo-body-illustration" aria-label="Illustrated muscle focus map"><div className="fo-human"><span className="head"/><span className="torso"/><span className="arm a1"/><span className="arm a2"/><span className="leg l1"/><span className="leg l2"/><i className="m chest"/><i className="m shoulder1"/><i className="m shoulder2"/><i className="m quad1"/><i className="m quad2"/></div><div className="fo-muscle-legend"><span><i/> Primary focus</span><b>CHEST · DELTS · QUADS</b><small>Dynamic maps can change by workout in production.</small></div></div></section>
<section className="fo-pattern-band"><span>FORM</span><i/> <span>LOAD</span><i/> <span>RANGE</span><i/> <span>TEMPO</span><i/> <span>RECOVERY</span><i/> <span>PROGRESS</span></section>
<section className="fo-section"><div className="fo-library-head"><div><Eyebrow>Choose the work</Eyebrow><h2 className="fo-display" style={{fontSize:"clamp(3rem,6vw,6.5rem)"}}>TRAINING THAT<br/><em>MEETS THE MOMENT.</em></h2></div><div className="fo-filter-pills">{["All","Muscle","Strength","Fat loss","Endurance","Recovery","Home"].map((x,i)=><button className={i===0?"active":""} key={x}>{x}</button>)}</div></div><div className="fo-guide-grid">{guides.map((g,i)=><article key={g[0]}><div className="fo-guide-photo" style={{backgroundImage:`linear-gradient(0deg,rgba(4,4,4,.84),transparent),url(${g[4]})`}}><span>{String(i+1).padStart(2,"0")}</span><button><Play size={18}/></button></div><small>{g[1]} · {g[2]}</small><h3>{g[0]}</h3><div><span><Clock3 size={12}/>{g[3]}</span><span><Dumbbell size={12}/> Equipment options</span></div><Link href="/vanta/app">Open guide →</Link></article>)}</div></section>
<section className="fo-section fo-technique"><div><Eyebrow>Technique breakdown</Eyebrow><h2 className="fo-display" style={{fontSize:"clamp(3rem,5.8vw,6rem)"}}>A GUIDE SHOULD<br/><em>TEACH THE REP.</em></h2><p className="fo-copy">Each exercise can show setup, execution, breathing, tempo, common mistakes, substitutions and the exact muscles involved.</p><CTA href="/vanta/form-check">Open Form Check</CTA></div><div className="fo-technique-stack">{[["01","SETUP","Feet planted. Ribcage stacked. Shoulder blades supported."],["02","DESCENT","Control the eccentric. Keep the wrist over the elbow."],["03","DRIVE","Press through the target line without losing shoulder position."],["04","PROGRESS","Add load only when range and control remain consistent."]].map(x=><article key={x[0]}><span>{x[0]}</span><div><b>{x[1]}</b><p>{x[2]}</p></div></article>)}</div></section>
<section className="fo-section"><Eyebrow>Recovery + education</Eyebrow><div className="fo-education-grid"><article><HeartPulse/><h3>Recovery guides</h3><p>Mobility, cooldowns, soreness-aware alternatives and recovery-day routines.</p></article><article><Activity/><h3>Progression guides</h3><p>Understand volume, intensity, tempo, RPE and when to progress a movement.</p></article><article><Dumbbell/><h3>Equipment guides</h3><p>Scan a station and open setup, safety notes and movement options for that machine.</p></article></div></section>
<section className="v-end"><div className="v-gridfx"/><Eyebrow>Knowledge becomes confidence</Eyebrow><h2>DON&apos;T JUST<br/>FOLLOW. <em>UNDERSTAND.</em></h2><p>Fitness Option can teach members how to train while keeping coaches at the center of the experience.</p><CTA href="/vanta/join">Start your program</CTA></section>
</main><Footer/></>}
