import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";

const lime="#D8FF45";
const leaders=[["01","Ada N.","4,820"],["02","Michael O.","4,510"],["03","Tola A.","4,120"],["04","Chidi K.","3,980"],["05","Amaka E.","3,770"]];

export default function Community(){return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} showsVerticalScrollIndicator={false}><Text style={s.kicker}>FITNESS OPTION · COMMUNITY</Text><Text style={s.title}>PROGRESS{"\n"}BECOMES{"\n"}CONTAGIOUS.</Text><Text style={s.copy}>Challenges, referrals and shareable wins give members a reason to bring people into the club.</Text>
<View style={s.challenge}><View style={s.live}><View style={s.liveDot}/><Text style={s.liveText}>LIVE CLUB CHALLENGE</Text></View><Text style={s.challengeTitle}>300,000{"\n"}REPS TOGETHER.</Text><Text style={s.copy}>Every logged rep moves the whole club toward the September target.</Text><View style={s.track}><View style={s.fill}/></View><View style={s.challengeFoot}><Text style={s.strong}>216,440 reps</Text><Text style={s.good}>72%</Text></View></View>
<View style={s.board}><Text style={s.label}>CLUB LEADERBOARD</Text>{leaders.map((x,i)=><View style={s.row} key={x[0]}><View style={[s.rank,i===0&&s.rankFirst]}><Text style={[s.rankText,i===0&&s.rankTextFirst]}>{x[0]}</Text></View><View style={s.name}><Text style={s.nameText}>{x[1]}</Text><Text style={s.note}>September challenge</Text></View><Text style={s.points}>{x[2]} pts</Text></View>)}</View>
<View style={s.referral}><Text style={s.label}>YOUR REFERRAL CIRCLE</Text><Text style={s.code}>MIKE-FO-24</Text><Text style={s.copy}>3 friends joined through your invite. Production rewards can be set by Fitness Option.</Text><View style={s.actions}><Pressable style={s.primary}><Text style={s.primaryText}>SHARE INVITE</Text></Pressable><Pressable style={s.secondary}><Text style={s.secondaryText}>COPY CODE</Text></Pressable></View></View>
</ScrollView></SafeAreaView>}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#090909"},page:{padding:20,paddingBottom:120},kicker:{fontSize:9,fontWeight:"900",letterSpacing:1.6,color:lime,marginTop:10},title:{fontSize:50,lineHeight:44,fontWeight:"900",letterSpacing:-3.5,color:"#F5F2EA",marginTop:16},copy:{color:"#8E8C85",fontSize:13,lineHeight:20,maxWidth:340,marginTop:13},challenge:{marginTop:24,borderWidth:1,borderColor:"#2A2A25",padding:20,backgroundColor:"#10100E"},live:{flexDirection:"row",alignItems:"center",gap:8},liveDot:{width:7,height:7,borderRadius:7,backgroundColor:lime},liveText:{fontSize:9,fontWeight:"900",letterSpacing:1.4,color:lime},challengeTitle:{fontSize:44,lineHeight:40,fontWeight:"900",letterSpacing:-3,color:"#F5F2EA",marginTop:18},track:{height:8,backgroundColor:"#2B2B26",marginTop:24},fill:{height:8,width:"72%",backgroundColor:lime},challengeFoot:{flexDirection:"row",justifyContent:"space-between",marginTop:10},strong:{color:"#F5F2EA",fontSize:12,fontWeight:"900"},good:{color:lime,fontSize:12,fontWeight:"900"},board:{marginTop:14,borderWidth:1,borderColor:"#2A2A25",padding:18,backgroundColor:"#0E0E0C"},label:{fontSize:9,fontWeight:"900",letterSpacing:1.5,color:"#7D7D76"},row:{flexDirection:"row",alignItems:"center",gap:12,paddingVertical:14,borderTopWidth:1,borderTopColor:"#282823"},rank:{width:34,height:34,borderRadius:17,borderWidth:1,borderColor:"#555",alignItems:"center",justifyContent:"center"},rankFirst:{borderColor:lime},rankText:{fontSize:9,color:"#888",fontWeight:"900"},rankTextFirst:{color:lime},name:{flex:1},nameText:{fontSize:12,fontWeight:"900",color:"#F5F2EA"},note:{fontSize:9,color:"#777",marginTop:3},points:{fontSize:14,fontWeight:"900",color:"#F5F2EA"},referral:{marginTop:14,padding:20,borderWidth:1,borderColor:"#2A2A25",backgroundColor:"#11110F"},code:{fontSize:36,fontWeight:"900",letterSpacing:3,color:"#F5F2EA",marginTop:22},actions:{flexDirection:"row",gap:10,marginTop:20},primary:{flex:1,padding:15,backgroundColor:lime,alignItems:"center"},primaryText:{color:"#090909",fontSize:9,fontWeight:"900",letterSpacing:1.2},secondary:{flex:1,padding:15,borderWidth:1,borderColor:"#3A3A34",alignItems:"center"},secondaryText:{color:"#EAE7DE",fontSize:9,fontWeight:"900",letterSpacing:1.2}})
