import { router } from "expo-router";
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";

const lime="#D8FF45";

export default function Today(){return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} showsVerticalScrollIndicator={false}>
<View style={s.top}><View><Text style={s.kicker}>FITNESS OPTION · MEMBER OS</Text><Text style={s.hello}>Good evening,{"\n"}Michael.</Text></View><View style={s.avatar}><Text style={s.avatarText}>MO</Text></View></View>
<View style={s.readiness}><View><Text style={s.kicker}>TODAY&apos;S READINESS</Text><Text style={s.score}>86<Text style={s.scoreSmall}>/100</Text></Text><Text style={s.muted}>High readiness · build quality work.</Text></View><View style={s.ring}><Text style={s.ringValue}>86</Text><Text style={s.ringLabel}>READY</Text></View></View>
<View style={s.metricRow}>{[["8.1h","Sleep"],["68","HRV"],["3/5","Soreness"]].map(x=><View style={s.metric} key={x[1]}><Text style={s.metricValue}>{x[0]}</Text><Text style={s.metricLabel}>{x[1]}</Text></View>)}</View>
<View style={s.session}><Text style={s.kicker}>NEXT SESSION · 18:30</Text><Text style={s.sessionTitle}>PUSH{"\n"}POWER</Text><Text style={s.muted}>Week 7 · Strength emphasis</Text><View style={s.chips}>{["Chest","Delts","Triceps"].map(x=><Text style={s.chip} key={x}>{x}</Text>)}</View><Pressable style={s.primary}><Text style={s.primaryText}>START SESSION</Text><Text style={s.primaryText}>↗</Text></Pressable></View>
<View style={s.ai}><View style={s.aiTop}><Text style={s.kicker}>FITNESS OPTION COACH AI</Text><Text style={s.live}>● LIVE</Text></View><Text style={s.aiTitle}>Today&apos;s load was adjusted.</Text><Text style={s.aiCopy}>Shoulder soreness is elevated, so overhead pressing changed to landmine press while preserving the target stimulus.</Text><View style={s.chips}>{["Energy 4/5","RPE 8","Soreness 3/5"].map(x=><Text style={s.darkChip} key={x}>{x}</Text>)}</View></View>
<View style={s.grid}><Pressable style={s.smallCard} onPress={()=>router.push("/progress")}><Text style={s.kicker}>STRENGTH INDEX</Text><Text style={s.bigNumber}>94.2</Text><Text style={s.good}>+14.2% since April</Text></Pressable><Pressable style={s.smallCard} onPress={()=>router.push("/community")}><Text style={s.kicker}>CLUB CHALLENGE</Text><Text style={s.bigNumber}>72%</Text><Text style={s.muted}>216,440 reps completed</Text></Pressable></View>
<Pressable style={s.formCheck}><View><Text style={s.kicker}>FORM CHECK · DEMO</Text><Text style={s.formTitle}>SEE THE REP.{"\n"}UNDERSTAND THE REP.</Text><Text style={s.muted}>Movement-analysis concept connected to your coach context.</Text></View><Text style={s.formArrow}>↗</Text></Pressable>
</ScrollView></SafeAreaView>}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#090909"},page:{padding:20,paddingBottom:120,gap:14},top:{flexDirection:"row",justifyContent:"space-between",alignItems:"flex-start",paddingTop:10},kicker:{fontSize:9,fontWeight:"900",letterSpacing:1.5,color:"#8B8B84"},hello:{fontSize:44,lineHeight:43,fontWeight:"900",letterSpacing:-2,color:"#F4F1E8",marginTop:12},avatar:{width:48,height:48,borderRadius:24,borderWidth:1,borderColor:"#43433F",alignItems:"center",justifyContent:"center"},avatarText:{color:lime,fontWeight:"900",fontSize:12},readiness:{marginTop:8,borderWidth:1,borderColor:"#272722",backgroundColor:"#10110E",padding:20,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},score:{fontSize:72,lineHeight:76,fontWeight:"900",letterSpacing:-5,color:"#F5F2E9",marginTop:7},scoreSmall:{fontSize:16,color:"#777"},muted:{color:"#8B8B84",fontSize:12,lineHeight:18},ring:{width:104,height:104,borderRadius:52,borderWidth:7,borderColor:lime,alignItems:"center",justifyContent:"center"},ringValue:{color:"#F5F2E9",fontSize:28,fontWeight:"900"},ringLabel:{color:"#777",fontSize:8,letterSpacing:1},metricRow:{flexDirection:"row",borderWidth:1,borderColor:"#272722"},metric:{flex:1,padding:15,borderRightWidth:1,borderRightColor:"#272722"},metricValue:{fontSize:20,fontWeight:"900",color:"#F5F2E9"},metricLabel:{fontSize:9,color:"#777",marginTop:3,textTransform:"uppercase",letterSpacing:1},session:{backgroundColor:lime,padding:22},sessionTitle:{fontSize:56,lineHeight:49,fontWeight:"900",letterSpacing:-4,color:"#090909",marginVertical:14},chips:{flexDirection:"row",flexWrap:"wrap",gap:7,marginTop:14},chip:{fontSize:9,fontWeight:"900",paddingHorizontal:10,paddingVertical:7,borderWidth:1,borderColor:"#7B921C",color:"#111"},darkChip:{fontSize:9,fontWeight:"800",paddingHorizontal:10,paddingVertical:7,backgroundColor:"#1E1E1B",color:"#B9B9B1"},primary:{marginTop:22,backgroundColor:"#090909",padding:16,flexDirection:"row",justifyContent:"space-between"},primaryText:{color:"white",fontSize:10,fontWeight:"900",letterSpacing:1.3},ai:{padding:20,borderWidth:1,borderColor:"#2A2A25",backgroundColor:"#0F0F0D"},aiTop:{flexDirection:"row",justifyContent:"space-between"},live:{color:lime,fontSize:8,fontWeight:"900",letterSpacing:1},aiTitle:{fontSize:24,fontWeight:"900",color:"#F5F2E9",letterSpacing:-1,marginTop:18},aiCopy:{fontSize:12,lineHeight:19,color:"#A4A39B",marginTop:8},grid:{flexDirection:"row",gap:12},smallCard:{flex:1,minHeight:160,padding:18,borderWidth:1,borderColor:"#282823",backgroundColor:"#10100E"},bigNumber:{fontSize:44,fontWeight:"900",letterSpacing:-3,color:"#F5F2E9",marginTop:22},good:{fontSize:10,color:lime,marginTop:5},formCheck:{minHeight:180,borderWidth:1,borderColor:"#2C2C27",padding:20,flexDirection:"row",justifyContent:"space-between",backgroundColor:"#12120F"},formTitle:{fontSize:27,lineHeight:25,fontWeight:"900",letterSpacing:-1.6,color:"#F5F2E9",marginVertical:16},formArrow:{fontSize:34,color:lime}}
