import { SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";

const lime="#D8FF45";

export default function Profile(){return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} showsVerticalScrollIndicator={false}><Text style={s.kicker}>FITNESS OPTION · MEMBER IDENTITY</Text><Text style={s.title}>YOUR CLUB.{"\n"}IN YOUR POCKET.</Text><Text style={s.copy}>Digital membership, check-in identity, training preferences and account controls live together.</Text>
<View style={s.pass}><View><Text style={s.active}>● ACTIVE MEMBER</Text><Text style={s.name}>MICHAEL{"\n"}OBI</Text><Text style={s.plan}>PERFORM MEMBERSHIP · APR 2026</Text><View style={s.tags}><Text style={s.tag}>LEVEL 07</Text><Text style={s.tag}>9 DAY STREAK</Text></View></View><View style={s.qr}><Text style={s.qrText}>FO{"\n"}QR</Text></View></View>
<View style={s.stats}>{[["42","Sessions"],["3","Friends joined"],["7","Achievements"]].map(x=><View style={s.stat} key={x[1]}><Text style={s.statValue}>{x[0]}</Text><Text style={s.statLabel}>{x[1]}</Text></View>)}</View>
<View style={s.section}><Text style={s.label}>TRAINING PROFILE</Text>{[["Primary goal","Build strength"],["Training days","4 / week"],["Session length","60 minutes"],["Coach","Kene Okafor"]].map(x=><View style={s.row} key={x[0]}><Text style={s.rowLabel}>{x[0]}</Text><Text style={s.rowValue}>{x[1]}</Text></View>)}</View>
<View style={s.section}><Text style={s.label}>ACCOUNT & PRIVACY</Text>{[["Progress sharing","Private by default"],["Story permission","Ask every time"],["Notifications","Training + coach"],["Data export","Available"]].map(x=><View style={s.row} key={x[0]}><Text style={s.rowLabel}>{x[0]}</Text><Text style={s.rowValue}>{x[1]}</Text></View>)}</View>
<Text style={s.footer}>Fitness Option · Performance engineered for people who take progress personally.</Text>
</ScrollView></SafeAreaView>}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#090909"},page:{padding:20,paddingBottom:120},kicker:{fontSize:9,fontWeight:"900",letterSpacing:1.6,color:lime,marginTop:10},title:{fontSize:48,lineHeight:44,fontWeight:"900",letterSpacing:-3.3,color:"#F5F2EA",marginTop:16},copy:{color:"#8E8C85",fontSize:13,lineHeight:20,maxWidth:340,marginTop:13},pass:{marginTop:24,minHeight:270,borderWidth:1,borderColor:"#34342E",backgroundColor:"#11110F",padding:22,flexDirection:"row",justifyContent:"space-between"},active:{color:lime,fontSize:9,fontWeight:"900",letterSpacing:1.3},name:{fontSize:44,lineHeight:39,fontWeight:"900",letterSpacing:-2.5,color:"#F5F2EA",marginTop:30},plan:{fontSize:9,color:"#77766F",fontWeight:"800",letterSpacing:1,marginTop:10},tags:{flexDirection:"row",gap:7,marginTop:20},tag:{fontSize:8,fontWeight:"900",color:"#C8C6BF",borderWidth:1,borderColor:"#373731",paddingHorizontal:9,paddingVertical:7},qr:{width:92,height:92,borderWidth:7,borderColor:"#F5F2EA",backgroundColor:"#1D1D19",alignItems:"center",justifyContent:"center"},qrText:{color:lime,fontWeight:"900",fontSize:18,textAlign:"center",letterSpacing:2},stats:{flexDirection:"row",borderWidth:1,borderColor:"#2A2A25",marginTop:12},stat:{flex:1,padding:16,borderRightWidth:1,borderRightColor:"#2A2A25"},statValue:{fontSize:27,fontWeight:"900",color:"#F5F2EA"},statLabel:{fontSize:8,color:"#777",textTransform:"uppercase",marginTop:4},section:{marginTop:14,borderWidth:1,borderColor:"#2A2A25",padding:18,backgroundColor:"#0E0E0C"},label:{fontSize:9,fontWeight:"900",letterSpacing:1.4,color:"#7D7D76",marginBottom:4},row:{paddingVertical:15,borderTopWidth:1,borderTopColor:"#282823",flexDirection:"row",justifyContent:"space-between",gap:15},rowLabel:{fontSize:11,color:"#8F8E87"},rowValue:{fontSize:11,color:"#F3F0E7",fontWeight:"800",textAlign:"right"},footer:{fontSize:10,color:"#5F5F59",lineHeight:16,textAlign:"center",marginTop:26}})
