import { SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";

const lime="#D8FF45";
const bars=[36,48,57,62,73,84,94];

export default function Progress(){return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} showsVerticalScrollIndicator={false}><Text style={s.kicker}>FITNESS OPTION · PROGRESS</Text><Text style={s.title}>MAKE THE WORK{"\n"}VISIBLE.</Text><Text style={s.copy}>Your training history should answer one question: are you actually moving forward?</Text>
<View style={s.hero}><Text style={s.label}>STRENGTH INDEX</Text><Text style={s.score}>94.2</Text><Text style={s.good}>↑ 14.2% since April</Text><View style={s.chart}>{bars.map((h,i)=><View key={i} style={[s.bar,{height:`${h}%`}]} />)}</View></View>
<View style={s.grid}>{[["102.5kg","Bench press","+5kg PB"],["162.5kg","Deadlift","+7.5kg PB"],["86","Readiness","Today"],["42","Sessions","12 weeks"]].map(x=><View style={s.card} key={x[1]}><Text style={s.cardValue}>{x[0]}</Text><Text style={s.cardTitle}>{x[1]}</Text><Text style={s.cardNote}>{x[2]}</Text></View>)}</View>
<View style={s.section}><Text style={s.label}>BODY METRICS · DEMO</Text>{[["Body weight","82.4 kg","−2.1 kg"],["Waist","84 cm","−4 cm"],["Resting HR","58 bpm","−6 bpm"]].map(x=><View style={s.row} key={x[0]}><Text style={s.rowName}>{x[0]}</Text><Text style={s.rowValue}>{x[1]}</Text><Text style={s.good}>{x[2]}</Text></View>)}</View>
<View style={s.section}><Text style={s.label}>CONSISTENCY</Text><View style={s.week}>{["M","T","W","T","F","S","S"].map((d,i)=><View key={`${d}${i}`} style={[s.day,i<4&&s.dayDone]}><Text style={[s.dayText,i<4&&s.dayTextDone]}>{d}</Text><Text style={[s.dot,i<4&&s.dotDone]}>{i<4?"✓":"·"}</Text></View>)}</View></View>
</ScrollView></SafeAreaView>}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#090909"},page:{padding:20,paddingBottom:120},kicker:{fontSize:9,fontWeight:"900",letterSpacing:1.6,color:lime,marginTop:10},title:{fontSize:52,lineHeight:47,fontWeight:"900",letterSpacing:-3.5,color:"#F5F2EA",marginTop:16},copy:{color:"#8E8C85",fontSize:13,lineHeight:20,maxWidth:320,marginTop:14,marginBottom:22},hero:{borderWidth:1,borderColor:"#292924",padding:20,backgroundColor:"#10100E"},label:{fontSize:9,fontWeight:"900",letterSpacing:1.4,color:"#7F7F78"},score:{fontSize:82,lineHeight:88,fontWeight:"900",letterSpacing:-6,color:"#F5F2EA",marginTop:10},good:{color:lime,fontSize:10,fontWeight:"800"},chart:{height:150,flexDirection:"row",alignItems:"flex-end",gap:7,marginTop:20,borderBottomWidth:1,borderBottomColor:"#30302B"},bar:{flex:1,backgroundColor:lime,opacity:.82},grid:{flexDirection:"row",flexWrap:"wrap",gap:10,marginTop:10},card:{width:"48.5%",minHeight:130,borderWidth:1,borderColor:"#292924",padding:16,backgroundColor:"#10100E"},cardValue:{fontSize:30,fontWeight:"900",letterSpacing:-1.5,color:"#F5F2EA"},cardTitle:{fontSize:11,fontWeight:"900",color:"#C8C7C0",marginTop:8},cardNote:{fontSize:9,color:"#77766F",marginTop:4},section:{marginTop:18,borderWidth:1,borderColor:"#292924",padding:18,backgroundColor:"#0E0E0C"},row:{paddingVertical:15,borderTopWidth:1,borderTopColor:"#272722",flexDirection:"row",alignItems:"center"},rowName:{flex:1,color:"#A6A49D",fontSize:11},rowValue:{color:"#F5F2EA",fontWeight:"900",fontSize:14,marginRight:18},week:{flexDirection:"row",gap:7,marginTop:16},day:{flex:1,aspectRatio:.75,borderWidth:1,borderColor:"#2B2B26",alignItems:"center",justifyContent:"space-between",paddingVertical:10},dayDone:{backgroundColor:lime,borderColor:lime},dayText:{fontSize:9,color:"#777"},dayTextDone:{color:"#111",fontWeight:"900"},dot:{color:"#777"},dotDone:{color:"#111",fontWeight:"900"}})
