"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, FileAudio, FileVideo2, ImageIcon, Search, Trash2, UploadCloud } from "lucide-react";
import { demoAssets, type MediaKind } from "../../../lib/cms";

const icons:Record<MediaKind,React.ReactNode>={image:<ImageIcon size={17}/>,video:<FileVideo2 size={17}/>,audio:<FileAudio size={17}/>};

export default function MediaLibrary(){const [kind,setKind]=useState<"all"|MediaKind>("all");const assets=demoAssets.filter(a=>kind==="all"||a.kind===kind);return <main className="cms-page"><section className="cms-hero"><div><Link className="ops-back" href="/admin/listings"><ArrowLeft size={15}/> Listings</Link><p className="eyebrow">Duches Media</p><h1>A visual and audio library built for hospitality storytelling.</h1><p>Organize hero photography, room galleries, vertical social videos, walkthroughs, voice notes, ambience tracks and campaign assets in one place.</p></div><label className="cms-primary upload-button"><UploadCloud size={16}/> Upload media<input type="file" multiple accept="image/*,video/*,audio/*"/></label></section><section className="cms-toolbar"><div className="cms-search"><Search size={16}/><input placeholder="Search media"/></div><div className="media-filters">{(["all","image","video","audio"] as const).map(x=><button key={x} className={kind===x?"active":""} onClick={()=>setKind(x)}>{x}</button>)}</div></section><section className="media-grid">{assets.map(asset=><article className="media-card" key={asset.id}><div className={`media-preview ${asset.kind}`} style={asset.kind!=="audio"?{backgroundImage:`url(${asset.url})`}:undefined}>{asset.kind==="audio"&&<FileAudio size={34}/>}<span>{icons[asset.kind]} {asset.kind}</span></div><div className="media-meta"><div><strong>{asset.name}</strong><small>{asset.duration??asset.size} · {asset.createdAt}</small></div><button aria-label={`Delete ${asset.name}`}><Trash2 size={16}/></button></div></article>)}</section><section className="storage-note"><UploadCloud size={21}/><div><strong>Storage-ready architecture</strong><p>The media UI is complete. Once Duches storage is provisioned, uploads will receive secure URLs, thumbnails and metadata and can be reused across website listings and social campaigns.</p></div></section></main>}
