import Link from "next/link";
import { ChevronRight, Flame, Play, SlidersHorizontal, Sparkles, TrendingUp, Trophy, ScanLine, Share2, QrCode, Users } from "lucide-react";
import { CardTitle, CheckDot, Droplets, OSShell, OSTop, Utensils } from "../ui";

export default function MemberOS(){return <OSShell role="member"><main className="v-os-main"><OSTop kicker="FITNESS OPTION MEMBER OS · SEPT 02" title="Good evening, Michael." copy="Your recovery is high. Today is built to move." links={[{href:"/vanta/community",label:"Community"},{href:"/vanta/trainer",label:"Coach view"}]}/><div className="v-os-grid">
<section className="v-ready-card" id="progress"><div><span>TODAY&apos;S READINESS</span><h2>86<small>/100</small></h2><p>You&apos;re primed for high quality work.</p></div><div className="v-donut"><div><b>86</b><small>READY</small></div></div><div className="v-read-metrics"><span><b>8.1h</b>Sleep</span><span><b>68</b>HRV</span><span><b>3/5</b>Soreness</span></div></section>
<section className="v-next-card" id="training"><span>NEXT SESSION · 18:30</span><h2>PUSH<br/>POWER</h2><p>Week 7 · Strength emphasis</p><div><span>Chest</span><span>Delts</span><span>Triceps</span></div><button>Start session <Play size={14}/></button></section>
<section className="v-os-card v-progress"><CardTitle kicker="STRENGTH INDEX" title="94.2"><TrendingUp size={18}/></CardTitle><span className="v-up">+14.2% since April</span><div className="v-sparkline"><i style={{height:"32%"}}/><i style={{height:"41%"}}/><i style={{height:"52%"}}/><i style={{height:"65%"}}/><i style={{height:"78%"}}/><i style={{height:"94%"}}/></div></section>
<section className="v-os-card v-workout"><CardTitle kicker="TODAY'S WORK" title="4 movements · 52 min"><SlidersHorizontal size={18}/></CardTitle>{[["Incline DB Press","4 × 8","32.5 kg"],["Cable Fly","3 × 12","17.5 kg"],["Landmine Press","3 × 10","25 kg"],["Rope Extension","3 × 15","27.5 kg"]].map((x,i)=><button className={i===0?"done":""} key={x[0]}>{i===0?<CheckDot/>:<span className="v-empty-dot"/>}<div><b>{x[0]}</b><small>{x[1]}</small></div><strong>{x[2]}</strong><ChevronRight size={14}/></button>)}</section>
<section className="v-os-card v-ai-card" id="coach-ai"><div className="v-ai-head"><Sparkles size={19}/><span><b>FITNESS OPTION COACH AI</b><small>Adjusted 11 min ago</small></span></div><p>Shoulder soreness is elevated, so today&apos;s overhead pressing changed to landmine press while preserving the target stimulus.</p><div className="v-ai-tags"><span>Energy 4/5</span><span>Soreness 3/5</span><span>RPE target 8</span></div><Link href="/vanta/form-check">Open Form Check →</Link></section>
<section className="v-os-card v-week"><CardTitle kicker="THIS WEEK" title="3 of 4 sessions"><Flame size={18}/></CardTitle><div className="v-week-dots">{["M","T","W","T","F","S","S"].map((x,i)=><div className={i<3?"done":i===3?"today":""} key={`${x}${i}`}><span>{x}</span><i>{i<3?"✓":i===3?"•":""}</i></div>)}</div><div className="v-macros"><span><Droplets size={13}/>2.4L / 3.2L</span><span><Utensils size={13}/>2,110 / 2,650 kcal</span></div></section>
<section className="v-os-card v-pb-card"><CardTitle kicker="LATEST WIN" title="New personal best"><Trophy size={18}/></CardTitle><h2>102.5<small>kg</small></h2><p>Bench press · +5kg from your previous best.</p><Link href="/vanta/community" style={{display:"inline-flex",gap:6,alignItems:"center",marginTop:12,color:"#d7ff37",fontSize:11}}>Share this win <Share2 size={13}/></Link></section>
</div>
<section style={{marginTop:"1rem"}}><div className="fo-app-rail"><article className="fo-app-module"><div className="fo-module-top"><span>FORM CHECK</span><ScanLine size={17}/></div><h3>Movement intelligence</h3><p>Record a supported exercise and review a simulated movement-analysis experience with coach cues and phase metrics.</p><Link href="/vanta/form-check" style={{color:"#d7ff37",fontSize:11}}>Try the experience →</Link></article><article className="fo-app-module"><div className="fo-module-top"><span>CLUB CHALLENGE</span><Users size={17}/></div><div className="fo-score">72<small>%</small></div><p>216,440 of 300,000 club reps completed this month.</p><Link href="/vanta/community" style={{color:"#d7ff37",fontSize:11}}>See leaderboard →</Link></article><article className="fo-app-module"><div className="fo-module-top"><span>REFERRAL REACH</span><Share2 size={17}/></div><h3>3 friends joined</h3><p>Your invite code MIKE-FO-24 is active. Production rewards can be configured by the owner.</p><Link href="/vanta/community" style={{color:"#d7ff37",fontSize:11}}>Open referral circle →</Link></article></div></section>
<section style={{marginTop:"1rem"}}><div className="fo-pass"><div><span className="fo-pulse"><i/>ACTIVE MEMBER</span><h4>MICHAEL OBI</h4><p>Perform Membership · Member since Apr 2026</p><div className="fo-social-proof"><span><Flame size={12}/> 9 day streak</span><span><Trophy size={12}/> Level 07</span><span><QrCode size={12}/> Club check-in</span></div></div><div className="fo-qr" aria-label="Demo membership QR code"/></div></section>
</main></OSShell>}
