import Link from "next/link";
import { ArrowUpRight, Target, Share2, Users, Flame, Megaphone } from "lucide-react";
import { CardTitle, OSShell, OSTop } from "../ui";

export default function AdminOS(){return <OSShell role="admin"><main className="v-os-main"><OSTop kicker="FITNESS OPTION OWNER COMMAND CENTER" title="Run the club from signals, not guesses." copy="Revenue, conversion, attendance, retention and word-of-mouth growth — in one decision layer." links={[{href:"/vanta/community",label:"Growth view"},{href:"/vanta/app",label:"Member view"}]}/><div className="v-admin-dash">
<section className="v-kpis"><K label="MONTHLY REVENUE" value="₦18.6m" note="Demo KPI · ↑12.4%"/><K label="ACTIVE MEMBERS" value="1,842" note="+76 net this month"/><K label="LEAD → MEMBER" value="31.8%" note="↑ 4.1 pts"/><K label="CHURN RISK" value="42" note="2.3% of members"/></section>
<section className="v-os-card v-revenue" id="revenue"><CardTitle kicker="REVENUE TREND" title="₦66m YTD sample"><span style={{fontSize:10,color:"#777"}}>Last 6 months</span></CardTitle><div className="v-bar-chart">{[["Apr",32],["May",39],["Jun",45],["Jul",47],["Aug",58],["Sep",66]].map(([m,v])=><div key={String(m)}><i style={{height:`${Number(v)*2.9}px`}}/><span>{m}</span></div>)}</div></section>
<section className="v-os-card v-funnel" id="leads"><CardTitle kicker="CONVERSION FUNNEL" title="September"><Target size={18}/></CardTitle>{[["New leads",286,100],["Assessments",164,57],["Trials",118,41],["Joined",91,32]].map(x=><article key={String(x[0])}><span><b>{x[0]}</b><small>{x[1]}</small></span><i><em style={{width:`${x[2]}%`}}/></i></article>)}</section>
<section className="v-os-card v-risk" id="members"><CardTitle kicker="RETENTION SIGNALS" title="Members to save"><span style={{fontSize:10,color:"#d7ff37"}}>42 flagged</span></CardTitle>{[["No visit in 10 days","18 members"],["Attendance down >40%","12 members"],["Plan ends in 7 days","8 members"],["Payment retry","4 members"]].map((x,i)=><article key={x[0]}><i>{i+1}</i><span><b>{x[0]}</b><small>{x[1]}</small></span><Link href="/vanta/trainer">Act <ArrowUpRight size={11}/></Link></article>)}</section>
</div>
<section style={{marginTop:"1rem"}}><div className="fo-app-rail"><article className="fo-app-module"><div className="fo-module-top"><span>REFERRAL ENGINE</span><Share2 size={17}/></div><div className="fo-score">64<small> leads</small></div><p>Demo referrals attributed to member invite codes this month. 21 have completed assessments.</p><Link href="/vanta/community" style={{color:"#d7ff37",fontSize:11}}>Review growth loop →</Link></article><article className="fo-app-module"><div className="fo-module-top"><span>COMMUNITY HEALTH</span><Flame size={17}/></div><h3>318 active streaks</h3><p>Members with a 3+ day activity streak are surfacing as the highest-engagement cohort.</p><Link href="/vanta/community" style={{color:"#d7ff37",fontSize:11}}>View challenges →</Link></article><article className="fo-app-module"><div className="fo-module-top"><span>SOCIAL REACH</span><Megaphone size={17}/></div><h3>127 share events</h3><p>Personal-best cards, challenge milestones and approved stories create trackable organic reach.</p><span style={{color:"#777",fontSize:11}}>Production analytics ready</span></article></div></section>
<section style={{marginTop:"1rem"}} className="fo-pass"><div><span className="fo-pulse"><i/>OWNER ACTION</span><h4>12 members need human follow-up today</h4><p>Prioritize people whose attendance dropped before sending another broad promotion. The trainer desk already ranks the outreach queue.</p><div className="fo-social-proof"><span><Users size={12}/> 12 outreach</span><span><Target size={12}/> 8 renewals</span><span><Share2 size={12}/> 21 referral assessments</span></div></div><Link className="v-cta" href="/vanta/trainer" style={{alignSelf:"center"}}>Open coach desk <ArrowUpRight size={16}/></Link></section>
</main></OSShell>}
function K({label,value,note}:{label:string;value:string;note:string}){return <article><span>{label}</span><b>{value}</b><small>{note}</small></article>}
