import Link from "next/link";
import { Activity, ArrowUpRight, Check, HeartPulse, QrCode, ScanLine, Trophy } from "lucide-react";
import { CTA, Eyebrow, Footer, PublicNav } from "./ui";

const hero="https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=2000&q=88";
const gym="https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1800&q=86";
const woman="https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=1400&q=86";
const trainer="https://images.unsplash.com/photo-1567013127542-490d757e51fc?auto=format&fit=crop&w=1400&q=86";

export default function VantaHome(){return <><PublicNav/><main className="v-public">
<section className="v-hero"><div className="v-hero-bg" style={{backgroundImage:`linear-gradient(90deg,rgba(6,6,6,.96) 0%,rgba(6,6,6,.66) 47%,rgba(6,6,6,.12) 82%),linear-gradient(0deg,#080808 0%,transparent 40%),url(${hero})`}}/><div className="v-gridfx"/><div className="v-hero-copy"><Eyebrow>Fitness Option · Performance Engineered.</Eyebrow><h1>ENGINEER<br/>YOUR <em>STRONGEST</em><br/>SELF.</h1><p>Training built around your body, your data and the version of you that refuses to stay average.</p><div className="v-hero-actions"><CTA>Start your assessment</CTA><CTA ghost href="#membership">Explore memberships</CTA></div></div><div className="v-orbit"><div className="v-orbit-ring"><span>F</span></div><div><small>LIVE CLUB LOAD</small><b>72%</b><span>Optimal training window</span></div></div><div className="v-hero-foot"><span><i/> FITNESS OPTION · PERFORMANCE FLOOR · LIVE</span><span>SCROLL TO ENTER ↓</span></div></section>
<section className="v-tape"><div>STRENGTH <i>•</i> CONDITIONING <i>•</i> RECOVERY <i>•</i> COACHING <i>•</i> PERFORMANCE <i>•</i> STRENGTH <i>•</i> CONDITIONING</div></section>
<section className="v-stats"><article><b>1,842</b><span>ACTIVE ATHLETES</span><small>Across every training level</small></article><article><b>92K+</b><span>SESSIONS COMPLETED</span><small>Tracked inside Fitness Option OS</small></article><article><b>+18.4%</b><span>AVG. STRENGTH GAIN</span><small>Member-reported 12 week trend</small></article><article><b>14,806</b><span>COACHED HOURS</span><small>Human expertise, data assisted</small></article></section>
<section className="v-section v-programs" id="programs"><div className="v-section-head"><div><Eyebrow>Your goal changes the system</Eyebrow><h2>DON&apos;T JOIN A GYM.<br/><em>ENTER A PROGRAM.</em></h2></div><p>Pick the outcome. We change the training architecture, recovery targets, coaching cadence and performance benchmarks around it.</p></div><div className="v-program-grid"><div className="v-goals"><article className="active"><span>01</span><div><b>Build muscle</b><small>Structured volume. Precision progression.</small></div><ArrowUpRight/></article><article><span>02</span><div><b>Lose fat</b><small>Performance-led conditioning, not punishment.</small></div><ArrowUpRight/></article><article><span>03</span><div><b>Build strength</b><small>Low-rep power with measurable progression.</small></div><ArrowUpRight/></article><article><span>04</span><div><b>Improve endurance</b><small>Run, row and cycle with intelligent load.</small></div><ArrowUpRight/></article><article><span>05</span><div><b>Athletic performance</b><small>Speed, power and resilient movement.</small></div><ArrowUpRight/></article></div><div className="v-program-shot" style={{backgroundImage:`linear-gradient(0deg,rgba(7,7,7,.92),rgba(7,7,7,.06)),url(${woman})`}}><span>PROGRAM MATCH · 96%</span><div><small>RECOMMENDED</small><h3>HYPERTROPHY LAB</h3><p>4 days / week · adaptive progression · coach review</p><Link href="/vanta/app">Preview the system <ArrowUpRight/></Link></div></div></div></section>
<section className="v-smart"><div className="v-smart-img" style={{backgroundImage:`url(${gym})`}}><div className="v-scanline"/><span><ScanLine size={17}/> SMART-FLOOR ENABLED</span></div><div className="v-smart-copy"><Eyebrow>The gym remembers</Eyebrow><h2>EVERY REP<br/>BECOMES <em>INTELLIGENCE.</em></h2><p>Scan equipment, open the right movement, log your set and leave the rest to Fitness Option OS. Your training history turns into the next decision.</p><div className="v-feature-lines"><article><Activity/><div><b>Adaptive load</b><small>Next-session targets based on completed work.</small></div></article><article><QrCode/><div><b>Equipment QR</b><small>Technique, setup and history at every station.</small></div></article><article><HeartPulse/><div><b>Recovery context</b><small>Readiness and soreness shape today&apos;s plan.</small></div></article></div><CTA href="/vanta/app">Enter Fitness Option OS</CTA></div></section>
<section className="v-app-preview v-section"><div className="v-section-head light"><div><Eyebrow>Inside Fitness Option OS</Eyebrow><h2>YOUR BODY.<br/><em>VISIBLE.</em></h2></div><p>A member experience designed to make progress impossible to ignore.</p></div><div className="v-phones"><article className="v-phone"><div className="v-phone-top">9:41 <span>● ●</span></div><small>GOOD EVENING, MICHAEL</small><h4>Push Day <em>07</em></h4><div className="v-ready"><div><b>86</b><small>READY</small></div><p>High readiness<br/><span>Sleep + recovery aligned</span></p></div><div className="v-bars"><i/><i/><i/><i/><i/></div></article><article className="v-phone middle"><div className="v-phone-top">9:41 <span>● ●</span></div><small>WEEKLY PROGRESSION</small><h4>+14.2% <em>↑</em></h4><div className="v-chartline"><i/><i/><i/><i/><i/><i/></div><div className="v-pb"><Trophy size={18}/><div><b>New personal best</b><span>Bench press · 102.5kg</span></div></div></article><article className="v-phone"><div className="v-phone-top">9:41 <span>● ●</span></div><small>FITNESS OPTION COACH AI</small><h4>Adjusting today&apos;s load.</h4><div className="v-ai-note">Your recovery is high, but shoulder soreness is 3/5. I kept total volume and changed overhead pressing to a neutral-grip variation.</div><div className="v-chips"><span>Sleep 8.1h</span><span>Energy 4/5</span><span>Soreness 3/5</span></div><Link href="/vanta/app">Review adjusted plan <ArrowUpRight size={14}/></Link></article></div></section>
<section className="v-section v-classes" id="classes"><div className="v-class-head"><div><Eyebrow>This week at Fitness Option</Eyebrow><h2>TRAIN TOGETHER.<br/><em>NOT GENERICALLY.</em></h2></div><CTA ghost href="/vanta/contact">Book a class</CTA></div><div className="v-class-list">{[["06:00","Foundry Strength","Maya","12/16","72"],["07:30","Engine 45","Tobi","18/20","90"],["17:00","Mobility Lab","Ada","9/14","58"],["18:30","Athletic Power","Ken","14/16","86"],["20:00","Restore","Nneka","8/12","62"]].map(x=><article key={x[1]}><span>{x[0]}</span><b>{x[1]}</b><small>Coach {x[2]}</small><div><i style={{width:`${x[4]}%`}}/></div><span>{x[3]}</span><Link href="/vanta/contact">Reserve <ArrowUpRight size={12}/></Link></article>)}</div></section>
<section className="v-coach" id="coaches"><div className="v-coach-img" style={{backgroundImage:`linear-gradient(0deg,rgba(5,5,5,.68),transparent),url(${trainer})`}}><div><span>HEAD PERFORMANCE COACH</span><h3>KENE<br/>OKAFOR</h3></div></div><div className="v-coach-copy"><Eyebrow>Human intelligence first</Eyebrow><blockquote>“The app doesn&apos;t replace coaching. It makes every conversation with your coach more precise.”</blockquote><div><span><b>12</b>Years coaching</span><span><b>380+</b>Athletes developed</span><span><b>CSCS</b>Performance certified</span></div><CTA ghost href="/vanta/trainer">Enter coach desk</CTA></div></section>
<section className="v-section v-membership" id="membership"><div className="v-member-intro"><Eyebrow>Fitness Option Membership</Eyebrow><h2>ACCESS IS EASY.<br/><em>COMMITMENT IS THE POINT.</em></h2><p>Start with the environment you need. Upgrade when your ambition does.</p></div><div className="v-plans"><Plan n="01" title="CLUB" price="₦45k" text="Train independently with full club and app access." items={["Performance floor access","Fitness Option OS training log","Unlimited standard classes","Monthly body metrics"]}/><Plan featured n="02" title="PERFORM" price="₦85k" text="Programming, recovery intelligence and coach accountability." items={["Everything in Club","Adaptive training program","2 coach reviews / month","Recovery & nutrition targets"]}/><Plan n="03" title="PRIVATE" price="Custom" text="A high-touch performance partnership built around you." items={["Dedicated performance coach","Private sessions","Weekly program design","Priority booking + concierge"]}/></div></section>
<section className="v-end"><div className="v-gridfx"/><Eyebrow>Start with a Fitness Option baseline</Eyebrow><h2>YOUR NEXT LEVEL<br/>NEEDS A <em>STARTING POINT.</em></h2><p>Book a 45-minute performance assessment. We measure, listen and design the next twelve weeks around the person standing in front of us.</p><CTA>Book Fitness Option assessment</CTA><small>No pressure. No generic sales tour.</small></section>
</main><Footer/></>}

function Plan({n,title,price,text,items,featured=false}:{n:string;title:string;price:string;text:string;items:string[];featured?:boolean}){return <article className={`v-plan ${featured?"featured":""}`}><div><span>{n}</span>{featured&&<b>MOST CHOSEN</b>}</div><h3>{title}</h3><strong>{price}<small>{price!=="Custom"?" / month":""}</small></strong><p>{text}</p><ul>{items.map(x=><li key={x}><Check size={14}/>{x}</li>)}</ul><CTA href="/vanta/contact">Choose {title.toLowerCase()}</CTA></article>}
