import Link from "next/link";
import { Activity, ArrowUpRight, Check, HeartPulse, QrCode, ScanLine, Trophy, Users, Share2, Smartphone, Sparkles } from "lucide-react";
import { CTA, Eyebrow, Footer, PublicNav } from "./ui";

const hero="https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=2000&q=88";
const gym="https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1800&q=86";
const woman="https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=1400&q=86";
const trainer="https://images.unsplash.com/photo-1567013127542-490d757e51fc?auto=format&fit=crop&w=1400&q=86";
const story1="https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=1600&q=84";
const story2="https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1200&q=82";
const story3="https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1200&q=82";

export default function FitnessOptionHome(){return <><PublicNav/><main className="v-public">
<section className="v-hero"><div className="v-hero-bg" style={{backgroundImage:`linear-gradient(90deg,rgba(6,6,6,.96) 0%,rgba(6,6,6,.66) 47%,rgba(6,6,6,.12) 82%),linear-gradient(0deg,#080808 0%,transparent 40%),url(${hero})`}}/><div className="v-gridfx"/><div className="v-hero-copy"><Eyebrow>Fitness Option · Performance Engineered.</Eyebrow><h1>ENGINEER<br/>YOUR <em>STRONGEST</em><br/>SELF.</h1><p>Training built around your body, your data and the version of you that refuses to stay average.</p><div className="v-hero-actions"><CTA href="/vanta/join">Join Fitness Option</CTA><CTA ghost href="/vanta/app">Explore Member OS</CTA></div></div><div className="v-orbit"><div className="v-orbit-ring"><span>F</span></div><div><small>LIVE CLUB LOAD</small><b>72%</b><span>Optimal training window</span></div></div><div className="v-hero-foot"><span><i/> FITNESS OPTION · PERFORMANCE FLOOR · LIVE</span><span>SCROLL TO ENTER ↓</span></div></section>
<section className="v-tape"><div>STRENGTH <i>•</i> CONDITIONING <i>•</i> RECOVERY <i>•</i> COACHING <i>•</i> COMMUNITY <i>•</i> PERFORMANCE <i>•</i> STRENGTH</div></section>
<section className="v-stats"><article><b>1,842</b><span>ACTIVE ATHLETES</span><small>Demo scale across every training level</small></article><article><b>92K+</b><span>SESSIONS COMPLETED</span><small>Tracked inside Fitness Option OS</small></article><article><b>318</b><span>ACTIVE STREAKS</span><small>Consistency made visible</small></article><article><b>31.8%</b><span>LEAD → MEMBER</span><small>Owner dashboard demo signal</small></article></section>
<section className="v-section v-programs" id="programs"><div className="v-section-head"><div><Eyebrow>Your goal changes the system</Eyebrow><h2>DON&apos;T JOIN A GYM.<br/><em>ENTER A PROGRAM.</em></h2></div><p>Pick the outcome. Fitness Option changes the training architecture, recovery targets, coaching cadence and performance benchmarks around it.</p></div><div className="v-program-grid"><div className="v-goals">{[["01","Build muscle","Structured volume. Precision progression."],["02","Lose fat","Performance-led conditioning, not punishment."],["03","Build strength","Low-rep power with measurable progression."],["04","Improve endurance","Run, row and cycle with intelligent load."],["05","Athletic performance","Speed, power and resilient movement."]].map((x,i)=><article className={i===0?"active":""} key={x[0]}><span>{x[0]}</span><div><b>{x[1]}</b><small>{x[2]}</small></div><ArrowUpRight/></article>)}</div><div className="v-program-shot" style={{backgroundImage:`linear-gradient(0deg,rgba(7,7,7,.92),rgba(7,7,7,.06)),url(${woman})`}}><span>PROGRAM MATCH · 96%</span><div><small>RECOMMENDED</small><h3>HYPERTROPHY LAB</h3><p>4 days / week · adaptive progression · coach review</p><Link href="/vanta/app">Preview the system <ArrowUpRight/></Link></div></div></div></section>
<section className="v-smart"><div className="v-smart-img" style={{backgroundImage:`url(${gym})`}}><div className="v-scanline"/><span><ScanLine size={17}/> SMART-FLOOR ENABLED</span></div><div className="v-smart-copy"><Eyebrow>The gym remembers</Eyebrow><h2>EVERY REP<br/>BECOMES <em>INTELLIGENCE.</em></h2><p>Scan equipment, open the right movement, log your set and leave the rest to Fitness Option OS. Training history becomes the next decision.</p><div className="v-feature-lines"><article><Activity/><div><b>Adaptive load</b><small>Next-session targets based on completed work.</small></div></article><article><QrCode/><div><b>Equipment QR</b><small>Technique, setup and history at every station.</small></div></article><article><HeartPulse/><div><b>Recovery context</b><small>Readiness and soreness shape today&apos;s plan.</small></div></article></div><CTA href="/vanta/app">Enter Fitness Option OS</CTA></div></section>
<section className="v-app-preview v-section"><div className="v-section-head light"><div><Eyebrow>Inside Fitness Option OS</Eyebrow><h2>YOUR BODY.<br/><em>VISIBLE.</em></h2></div><p>A member experience designed to make progress impossible to ignore.</p></div><div className="v-phones"><article className="v-phone"><div className="v-phone-top">9:41 <span>● ●</span></div><small>GOOD EVENING, MICHAEL</small><h4>Push Day <em>07</em></h4><div className="v-ready"><div><b>86</b><small>READY</small></div><p>High readiness<br/><span>Sleep + recovery aligned</span></p></div><div className="v-bars"><i/><i/><i/><i/><i/></div></article><article className="v-phone middle"><div className="v-phone-top">9:41 <span>● ●</span></div><small>WEEKLY PROGRESSION</small><h4>+14.2% <em>↑</em></h4><div className="v-chartline"><i/><i/><i/><i/><i/><i/></div><div className="v-pb"><Trophy size={18}/><div><b>New personal best</b><span>Bench press · 102.5kg</span></div></div></article><article className="v-phone"><div className="v-phone-top">9:41 <span>● ●</span></div><small>FITNESS OPTION COACH AI</small><h4>Adjusting today&apos;s load.</h4><div className="v-ai-note">Recovery is high, but shoulder soreness is 3/5. Keep the stimulus, change the movement.</div><div className="v-chips"><span>Sleep 8.1h</span><span>Energy 4/5</span><span>Soreness 3/5</span></div><Link href="/vanta/form-check">Open Form Check <ArrowUpRight size={14}/></Link></article></div></section>
<section className="fo-section" id="stories"><Eyebrow>Transformation stories · demo content</Eyebrow><h2 className="fo-display">THE RESULT ISN&apos;T<br/>A PHOTO. <em>IT&apos;S A STORY.</em></h2><p className="fo-copy">Fitness Option can turn approved member journeys into premium social proof without reducing people to unrealistic before-and-after promises.</p><div className="fo-story-grid"><article className="fo-story-main"><img src={story1} alt="Athlete training"/><div className="fo-story-content"><small>12 week strength journey</small><h3>ADA BUILT<br/>THE HABIT FIRST.</h3><p>Her win was consistency: 42 logged sessions, a stronger squat pattern and a routine she could sustain around work.</p></div></article><div className="fo-story-stack"><article className="fo-story-small"><img src={story2} alt="Gym training"/><div className="fo-story-content"><small>Member story</small><h3>FROM RANDOM TO STRUCTURED.</h3></div></article><article className="fo-story-small"><img src={story3} alt="Coach supporting athlete"/><div className="fo-story-content"><small>Coach partnership</small><h3>PROGRESS WITH CONTEXT.</h3></div></article></div></div></section>
<section className="fo-community-band"><div className="fo-community-copy"><Eyebrow>Fitness Option Community</Eyebrow><h2 className="fo-display">MAKE<br/>PROGRESS <em>CONTAGIOUS.</em></h2><p className="fo-copy">Club challenges, streaks, shareable personal records and referrals give members reasons to bring their friends into the experience.</p><CTA href="/vanta/community">Enter the community</CTA></div><div className="fo-community-stage"><span className="fo-pulse"><i/>LIVE CLUB CHALLENGE</span><h3 style={{fontSize:"clamp(2.8rem,5vw,5.4rem)",lineHeight:.9,margin:".5rem 0 1.5rem",letterSpacing:"-.055em"}}>300,000<br/>REPS TOGETHER.</h3><div className="fo-leaderboard">{[["01","Ada N.","4,820 pts"],["02","Michael O.","4,510 pts"],["03","Tola A.","4,120 pts"],["04","Chidi K.","3,980 pts"]].map(x=><article key={x[0]}><span className="fo-rank">{x[0]}</span><span><b>{x[1]}</b><small style={{display:"block"}}>September challenge</small></span><strong>{x[2]}</strong></article>)}</div></div></section>
<section className="fo-section"><div className="fo-referral"><div><Eyebrow>Built-in word of mouth</Eyebrow><h2 className="fo-display" style={{fontSize:"clamp(3rem,6vw,6.7rem)"}}>MEMBERS BECOME<br/><em>THE MEDIA.</em></h2><p className="fo-copy">Referral identity, shareable personal-best cards, transformation stories and challenge badges turn member success into Fitness Option reach.</p></div><div className="fo-referral-card"><span className="fo-pulse"><i/>PERSONAL INVITE</span><div className="fo-code">MIKE-FO-24</div><p>Invite a friend. When they complete a Fitness Option assessment, both profiles unlock a referral reward in the production version.</p><div className="fo-share"><span><Share2 size={13}/> Share invite</span><span>Copy code</span><span>3 friends joined</span></div></div></div></section>
<section className="fo-section" style={{paddingTop:"2rem"}}><Eyebrow>The product behind the brand</Eyebrow><h2 className="fo-display" style={{fontSize:"clamp(3rem,6vw,6.5rem)"}}>A GYM PEOPLE<br/><em>CAN FEEL IN THEIR PHONE.</em></h2><div className="fo-tech-grid"><article><Smartphone/><div><h3>Member OS</h3><p>Workout plans, readiness, progress, nutrition, classes, messages, achievements and digital membership identity.</p></div><small>iOS + Android</small></article><article><Sparkles/><div><h3>Coach intelligence</h3><p>Adaptive check-ins, program context and a pathway to production AI coaching without replacing trainers.</p></div><small>Personalized</small></article><article><ScanLine/><div><h3>Form Check</h3><p>A premium simulated movement-analysis concept ready for a real computer-vision integration in a later phase.</p></div><small><Link href="/vanta/form-check">View experience →</Link></small></article><article><Users/><div><h3>Growth engine</h3><p>Challenges, referrals, member stories and retention signals connect the product directly to business growth.</p></div><small><Link href="/vanta/admin">Owner view →</Link></small></article></div></section>
<section className="v-section v-classes" id="classes"><div className="v-class-head"><div><Eyebrow>This week at Fitness Option</Eyebrow><h2>TRAIN TOGETHER.<br/><em>NOT GENERICALLY.</em></h2></div><CTA ghost href="/vanta/join">Book a class</CTA></div><div className="v-class-list">{[["06:00","Foundry Strength","Maya","12/16","72"],["07:30","Engine 45","Tobi","18/20","90"],["17:00","Mobility Lab","Ada","9/14","58"],["18:30","Athletic Power","Ken","14/16","86"],["20:00","Restore","Nneka","8/12","62"]].map(x=><article key={x[1]}><span>{x[0]}</span><b>{x[1]}</b><small>Coach {x[2]}</small><div><i style={{width:`${x[4]}%`}}/></div><span>{x[3]}</span><Link href="/vanta/join">Reserve <ArrowUpRight size={12}/></Link></article>)}</div></section>
<section className="v-coach" id="coaches"><div className="v-coach-img" style={{backgroundImage:`linear-gradient(0deg,rgba(5,5,5,.68),transparent),url(${trainer})`}}><div><span>HEAD PERFORMANCE COACH</span><h3>KENE<br/>OKAFOR</h3></div></div><div className="v-coach-copy"><Eyebrow>Human intelligence first</Eyebrow><blockquote>“The app doesn&apos;t replace coaching. It makes every conversation with your coach more precise.”</blockquote><div><span><b>12</b>Years coaching</span><span><b>380+</b>Athletes developed</span><span><b>CSCS</b>Performance certified</span></div><CTA ghost href="/vanta/trainer">Enter coach desk</CTA></div></section>
<section className="v-section v-membership" id="membership"><div className="v-member-intro"><Eyebrow>Fitness Option Membership · sample architecture</Eyebrow><h2>ACCESS IS EASY.<br/><em>COMMITMENT IS THE POINT.</em></h2><p>Sample demo tiers are shown here and can be replaced with Fitness Option&apos;s real pricing and benefits.</p></div><div className="v-plans"><Plan n="01" title="CLUB" price="₦45k" text="Train independently with full club and app access." items={["Performance floor access","Fitness Option OS training log","Unlimited standard classes","Monthly body metrics"]}/><Plan featured n="02" title="PERFORM" price="₦85k" text="Programming, recovery intelligence and coach accountability." items={["Everything in Club","Adaptive training program","2 coach reviews / month","Recovery & nutrition targets"]}/><Plan n="03" title="PRIVATE" price="Custom" text="A high-touch performance partnership built around you." items={["Dedicated performance coach","Private sessions","Weekly program design","Priority booking + concierge"]}/></div></section>
<section className="v-end"><div className="v-gridfx"/><Eyebrow>Start with a Fitness Option baseline</Eyebrow><h2>YOUR NEXT LEVEL<br/>NEEDS A <em>STARTING POINT.</em></h2><p>Book a 45-minute performance assessment. Fitness Option measures, listens and designs the next phase around the person standing in front of the coach.</p><CTA href="/vanta/join">Start Fitness Option journey</CTA><small>Client demonstration experience · production details are configurable.</small></section>
</main><Footer/></>}

function Plan({n,title,price,text,items,featured=false}:{n:string;title:string;price:string;text:string;items:string[];featured?:boolean}){return <article className={`v-plan ${featured?"featured":""}`}><div><span>{n}</span>{featured&&<b>MOST CHOSEN</b>}</div><h3>{title}</h3><strong>{price}<small>{price!=="Custom"?" / month":""}</small></strong><p>{text}</p><ul>{items.map(x=><li key={x}><Check size={14}/>{x}</li>)}</ul><CTA href="/vanta/join">Choose {title.toLowerCase()}</CTA></article>}
