import Link from "next/link";
import { ArrowUpRight, Activity, CalendarDays, Dumbbell, MessageCircle, Sparkles, TrendingUp, Users, WalletCards, Target, UserRoundCog, Settings, LogOut, Trophy, Droplets, Utensils, Bell, Search, Check, ChevronRight, Flame, ShieldCheck, ScanLine, Radio, BookOpen, CalendarCheck2 } from "lucide-react";

export function Brand(){return <Link className="v-brand" href="/vanta"><span className="v-mark"><i/><b/></span><span>FITNESS OPTION<small>PERFORMANCE CLUB</small></span></Link>}
export function PublicNav(){return <header className="v-head"><Brand/><nav><Link href="/vanta#programs">Training</Link><Link href="/vanta/live">Live</Link><Link href="/vanta/guides">Guides</Link><Link href="/vanta/community">Community</Link><Link href="/vanta/app">Member OS</Link></nav><div><Link className="v-sign" href="/vanta/app">Sign in</Link><Link className="v-mini" href="/vanta/join">Join Fitness Option <ArrowUpRight size={15}/></Link></div></header>}
export function Eyebrow({children}:{children:React.ReactNode}){return <div className="v-eye"><span/>{children}</div>}
export function CTA({href="/vanta/contact",children,ghost=false}:{href?:string;children:React.ReactNode;ghost?:boolean}){return <Link className={`v-cta ${ghost?"ghost":""}`} href={href}>{children}<ArrowUpRight size={17}/></Link>}
export function Footer(){return <footer className="v-footer"><Brand/><p>Performance engineered in Lagos.<br/>Built for people who take progress personally.</p><div><Link href="/vanta/live">Live</Link><Link href="/vanta/guides">Guides</Link><Link href="/vanta/community">Community</Link><Link href="/vanta/join">Join</Link></div><small>© 2026 Fitness Option · Client demonstration experience</small></footer>}

type NavItem=readonly [string,React.ComponentType<{size?:number}>,string];
const memberItems:readonly NavItem[]=[["Overview",Activity,"/vanta/app"],["Today Plan",CalendarCheck2,"/vanta/daily"],["Training",Dumbbell,"/vanta/app#training"],["Live",Radio,"/vanta/live"],["Guides",BookOpen,"/vanta/guides"],["Progress",TrendingUp,"/vanta/app#progress"],["Coach AI",Sparkles,"/vanta/app#coach-ai"],["Form Check",ScanLine,"/vanta/form-check"],["Community",Trophy,"/vanta/community"]] as const;
const trainerItems:readonly NavItem[]=[["Overview",Activity,"/vanta/trainer"],["Clients",Users,"/vanta/trainer#clients"],["Programming",Dumbbell,"/vanta/trainer#programming"],["Publish",BookOpen,"/vanta/trainer#publish"],["Go Live",Radio,"/vanta/live"],["Schedule",CalendarDays,"/vanta/trainer#schedule"],["Member OS",TrendingUp,"/vanta/app"],["Community",Trophy,"/vanta/community"]] as const;
const adminItems:readonly NavItem[]=[["Command center",Activity,"/vanta/admin"],["Members",Users,"/vanta/admin#members"],["Revenue",WalletCards,"/vanta/admin#revenue"],["Leads",Target,"/vanta/admin#leads"],["Live + Content",Radio,"/vanta/admin#content"],["Classes",CalendarDays,"/vanta#classes"],["Coaches",UserRoundCog,"/vanta/trainer"],["Growth",TrendingUp,"/vanta/community"]] as const;
export function OSShell({role,children}:{role:"member"|"trainer"|"admin";children:React.ReactNode}){const items=role==="member"?memberItems:role==="trainer"?trainerItems:adminItems;const person=role==="member"?["MO","Michael Obi","Perform member"]:role==="trainer"?["KO","Kene Okafor","Head coach"]:["FO","Fitness Option Owner","Admin access"];return <div className="v-os"><aside><Brand/><div className="v-profile"><div>{person[0]}</div><span><b>{person[1]}</b><small>{person[2]}</small></span></div><nav>{items.map(([label,Icon,href],i)=><Link className={`fo-os-nav ${i===0?"active":""}`} href={href} key={label}><Icon size={16}/>{label}</Link>)}</nav><div className="v-side-bottom"><Link href="/vanta">← Public site</Link><Link href="/vanta" className="fo-signout"><LogOut size={16}/>Exit demo</Link></div></aside>{children}</div>}
export function OSTop({kicker,title,copy,links=[]}:{kicker:string;title:string;copy:string;links?:{href:string;label:string}[]}){return <div className="v-os-top"><div><small>{kicker}</small><h1>{title}</h1><p>{copy}</p></div><div className="v-top-tools"><Link href="/vanta/guides" aria-label="Search guides"><Search size={15}/></Link><Link href="/vanta/community" aria-label="Notifications"><Bell size={15}/><i/></Link>{links.map(x=><Link href={x.href} key={x.href}>{x.label}</Link>)}</div></div>}
export function CardTitle({kicker,title,children}:{kicker:string;title:string;children?:React.ReactNode}){return <div className="v-card-title"><div><span>{kicker}</span><h3>{title}</h3></div>{children}</div>}
export function CheckDot(){return <span className="v-checkdot"><Check size={11}/></span>}
export {ArrowUpRight,Activity,CalendarDays,Dumbbell,MessageCircle,Sparkles,TrendingUp,Users,WalletCards,Target,UserRoundCog,Settings,Trophy,Droplets,Utensils,Bell,Search,Check,ChevronRight,Flame,ShieldCheck,ScanLine,Radio,BookOpen,CalendarCheck2};
