import Link from "next/link";
import { ArrowUpRight, Activity, CalendarDays, Dumbbell, MessageCircle, Sparkles, TrendingUp, Users, WalletCards, Target, UserRoundCog, Settings, LogOut, Trophy, Droplets, Utensils, Bell, Search, Check, ChevronRight, Flame, ShieldCheck } from "lucide-react";

export function Brand(){return <Link className="v-brand" href="/vanta"><span className="v-mark"><i/><b/></span><span>FITNESS OPTION<small>PERFORMANCE CLUB</small></span></Link>}
export function PublicNav(){return <header className="v-head"><Brand/><nav><Link href="/vanta#programs">Training</Link><Link href="/vanta#classes">Classes</Link><Link href="/vanta#coaches">Coaches</Link><Link href="/vanta#membership">Membership</Link><Link href="/vanta/app">Member OS</Link></nav><div><Link className="v-sign" href="/vanta/app">Sign in</Link><Link className="v-mini" href="/vanta/contact">Join Fitness Option <ArrowUpRight size={15}/></Link></div></header>}
export function Eyebrow({children}:{children:React.ReactNode}){return <div className="v-eye"><span/>{children}</div>}
export function CTA({href="/vanta/contact",children,ghost=false}:{href?:string;children:React.ReactNode;ghost?:boolean}){return <Link className={`v-cta ${ghost?"ghost":""}`} href={href}>{children}<ArrowUpRight size={17}/></Link>}
export function Footer(){return <footer className="v-footer"><Brand/><p>Performance engineered in Lagos.<br/>Built for people who take progress personally.</p><div><Link href="/vanta#programs">Training</Link><Link href="/vanta#membership">Membership</Link><Link href="/vanta/app">Member OS</Link><Link href="/vanta/contact">Contact</Link></div><small>© 2026 Fitness Option · Client demonstration experience</small></footer>}

const memberItems=[["Overview",Activity],["Training",Dumbbell],["Progress",TrendingUp],["Coach AI",Sparkles],["Nutrition",Utensils],["Classes",CalendarDays],["Messages",MessageCircle]] as const;
const trainerItems=[["Overview",Activity],["Clients",Users],["Programming",Dumbbell],["Schedule",CalendarDays],["Messages",MessageCircle],["Reports",TrendingUp]] as const;
const adminItems=[["Command center",Activity],["Members",Users],["Revenue",WalletCards],["Leads",Target],["Classes",CalendarDays],["Coaches",UserRoundCog],["Settings",Settings]] as const;
export function OSShell({role,children}:{role:"member"|"trainer"|"admin";children:React.ReactNode}){const items=role==="member"?memberItems:role==="trainer"?trainerItems:adminItems;const person=role==="member"?["MO","Michael Obi","Perform member"]:role==="trainer"?["KO","Kene Okafor","Head coach"]:["FO","Fitness Option Owner","Admin access"];return <div className="v-os"><aside><Brand/><div className="v-profile"><div>{person[0]}</div><span><b>{person[1]}</b><small>{person[2]}</small></span></div><nav>{items.map(([label,Icon],i)=><button className={i===0?"active":""} key={label}><Icon size={16}/>{label}</button>)}</nav><div className="v-side-bottom"><Link href="/vanta">← Public site</Link><button><LogOut size={16}/>Sign out</button></div></aside>{children}</div>}
export function OSTop({kicker,title,copy,links=[]}:{kicker:string;title:string;copy:string;links?:{href:string;label:string}[]}){return <div className="v-os-top"><div><small>{kicker}</small><h1>{title}</h1><p>{copy}</p></div><div className="v-top-tools"><button><Search size={15}/></button><button><Bell size={15}/><i/></button>{links.map(x=><Link href={x.href} key={x.href}>{x.label}</Link>)}</div></div>}
export function CardTitle({kicker,title,children}:{kicker:string;title:string;children?:React.ReactNode}){return <div className="v-card-title"><div><span>{kicker}</span><h3>{title}</h3></div>{children}</div>}
export function CheckDot(){return <span className="v-checkdot"><Check size={11}/></span>}
export {ArrowUpRight,Activity,CalendarDays,Dumbbell,MessageCircle,Sparkles,TrendingUp,Users,WalletCards,Target,UserRoundCog,Settings,Trophy,Droplets,Utensils,Bell,Search,Check,ChevronRight,Flame,ShieldCheck};
