import Link from "next/link";
import { CalendarDays, ChevronRight, Sparkles, ScanLine, MessageCircle, TrendingUp } from "lucide-react";
import { CardTitle, OSShell, OSTop } from "../ui";

export default function TrainerOS(){return <OSShell role="trainer"><main className="v-os-main"><OSTop kicker="FITNESS OPTION COACH DESK" title="Your athletes need three decisions." copy="Prioritized by adherence, recovery, movement feedback and upcoming sessions." links={[{href:"/vanta/admin",label:"Owner view"},{href:"/vanta/form-check",label:"Form Check"}]}/><div className="v-coach-dash">
<section className="v-kpis"><K label="ACTIVE CLIENTS" value="38" note="+4 this month"/><K label="ADHERENCE" value="87%" note="Target 85%"/><K label="SESSIONS TODAY" value="11" note="Next at 07:30"/><K label="RETENTION" value="94%" note="90-day rolling"/></section>
<section className="v-os-card v-clients" id="clients"><CardTitle kicker="CLIENT PRIORITY" title="Needs attention"><span style={{fontSize:10,color:"#d7ff37"}}>Ranked automatically</span></CardTitle>{[["Michael Obi","Strength","92%","Ready 86","Review load"],["Amaka Eze","Fat loss","74%","Missed 2","Message"],["David Cole","Muscle","88%","Sore 4/5","Adapt"],["Tola Akin","Endurance","81%","Ready 71","Check-in"]].map((r,i)=><article key={r[0]}><div className="v-avatar">{r[0].split(" ").map(x=>x[0]).join("")}</div><b>{r[0]}</b><span>{r[1]}</span><span>{r[2]} adherence</span><span className={i===1||i===2?"warn":""}>{r[3]}</span><Link href={i===0?"/vanta/app":i===2?"/vanta/form-check":"/vanta/community"}>{r[4]} <ChevronRight size={12}/></Link></article>)}</section>
<section className="v-os-card v-appts" id="schedule"><CardTitle kicker="TODAY" title="Appointments"><CalendarDays size={18}/></CardTitle>{[["07:30","Ada","Assessment"],["09:00","Michael","Strength"],["12:30","Chidi","Review"],["17:00","Amaka","PT session"]].map(x=><article key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><small>{x[2]}</small></article>)}</section>
</div>
<section id="programming" style={{marginTop:"1rem"}}><div className="fo-app-rail"><article className="fo-app-module"><div className="fo-module-top"><span>PROGRAMMING QUEUE</span><Sparkles size={17}/></div><h3>6 plans need review</h3><p>Three athletes completed their current block, two have recovery flags and one missed the planned progression threshold.</p><Link href="/vanta/app" style={{color:"#d7ff37",fontSize:11}}>Preview member context →</Link></article><article className="fo-app-module"><div className="fo-module-top"><span>MOVEMENT REVIEW</span><ScanLine size={17}/></div><h3>4 Form Checks</h3><p>Demo movement reviews are ready for coach interpretation and technique follow-up.</p><Link href="/vanta/form-check" style={{color:"#d7ff37",fontSize:11}}>Open Form Check →</Link></article><article className="fo-app-module"><div className="fo-module-top"><span>OUTREACH</span><MessageCircle size={17}/></div><h3>12 members to contact</h3><p>Attendance and adherence signals suggest these members need a human message before a generic promotion.</p><Link href="/vanta/admin" style={{color:"#d7ff37",fontSize:11}}>See retention signals →</Link></article></div></section>
<section style={{marginTop:"1rem"}} className="fo-pass"><div><span className="fo-pulse"><i/>COACH IMPACT</span><h4>94% client retention · 87% average adherence</h4><p>The production version can turn trainer performance into a fair coaching-quality view using attendance, program adherence, member feedback and renewals.</p><div className="fo-social-proof"><span><TrendingUp size={12}/> +4 active clients</span><span><CalendarDays size={12}/> 11 sessions today</span><span><Sparkles size={12}/> 6 programs to review</span></div></div></section>
</main></OSShell>}
function K({label,value,note}:{label:string;value:string;note:string}){return <article><span>{label}</span><b>{value}</b><small>{note}</small></article>}
