"use client";
import {useMemo,useState} from "react";
import {CalendarDays,Car,ChefHat,Plane,ShieldCheck,Sparkles,Users} from "lucide-react";

type Props={slug:string;name:string;maxGuests:number;currency?:string};
const extras=[
 {id:"airport",label:"Airport transfer",icon:Plane},
 {id:"chauffeur",label:"Private chauffeur",icon:Car},
 {id:"chef",label:"Private chef",icon:ChefHat},
 {id:"security",label:"Executive security",icon:ShieldCheck},
];
export default function BookingExperience({slug,name,maxGuests,currency="USD"}:Props){
 const[start,setStart]=useState("");const[end,setEnd]=useState("");const[guests,setGuests]=useState(2);const[selected,setSelected]=useState<string[]>([]);const[email,setEmail]=useState("");const[phone,setPhone]=useState("");const[nameValue,setNameValue]=useState("");const[state,setState]=useState<any>(null);const[busy,setBusy]=useState(false);
 const nights=useMemo(()=>start&&end?Math.max(0,Math.ceil((new Date(end).getTime()-new Date(start).getTime())/86400000)):0,[start,end]);
 function toggle(id:string){setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
 async function request(){setBusy(true);setState(null);const r=await fetch('/api/booking/quote',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({slug,startDate:start,endDate:end,guests,extras:selected,client:{name:nameValue,email,phone}})});const d=await r.json();setState(d);setBusy(false)}
 return <section className="booking-experience"><div className="booking-exp-head"><div><p className="eyebrow dark-eye">Reserve your stay</p><h2>Build your Duches experience.</h2><p>Select dates, guests and private services. Final availability and any non-published pricing remain subject to Duches confirmation.</p></div><Sparkles size={26}/></div><div className="booking-exp-grid"><div className="booking-exp-form"><div className="date-grid"><label>Arrival<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Departure<input type="date" value={end} min={start} onChange={e=>setEnd(e.target.value)}/></label><label>Guests<select value={guests} onChange={e=>setGuests(Number(e.target.value))}>{Array.from({length:Math.max(1,maxGuests)},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label></div><h3>Enhance your stay</h3><div className="extras-grid">{extras.map(x=>{const Icon=x.icon;return <button type="button" className={selected.includes(x.id)?"extra-card active":"extra-card"} onClick={()=>toggle(x.id)} key={x.id}><Icon size={19}/><span>{x.label}</span></button>})}</div><div className="guest-grid"><label>Full name<input value={nameValue} onChange={e=>setNameValue(e.target.value)} placeholder="Your name"/></label><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="you@example.com"/></label><label>Phone / WhatsApp<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+234 ..."/></label></div><button className="gold-button" disabled={busy||!start||!end||!email||!nameValue} onClick={request}>{busy?'Preparing request…':'Request availability & quote'}</button>{state?.error&&<p className="booking-error">{state.error}</p>}</div><aside className="booking-summary"><p className="eyebrow">Private stay summary</p><h3>{name}</h3><div><span><CalendarDays size={15}/> {nights||0} night{nights===1?'':'s'}</span><span><Users size={15}/> {guests} guest{guests===1?'':'s'}</span></div><p>{selected.length?`${selected.length} concierge enhancement${selected.length===1?'':'s'} selected`:'Add chauffeur, chef, transfers or security as needed.'}</p>{state?.ok&&<div className="quote-result"><strong>{state.status==='available'?'Dates currently available':'Request received'}</strong>{state.quote?.total&&<b>{currency} {Number(state.quote.total).toLocaleString()}</b>}<p>{state.message}</p>{state.bookingReference&&<a className="outline-gold" href={`/client/itinerary/${state.bookingReference}`}>View request itinerary</a>}</div>}</aside></div></section>
}
