import Link from "next/link";
import { CalendarDays, Clock3, Heart, MessageCircle, Play, Radio, Users, Video } from "lucide-react";
import { CTA, Eyebrow, Footer, PublicNav } from "../ui";

const liveHero="https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1800&q=88";
const replayA="https://images.unsplash.com/photo-1549060279-7e168fcee0c2?auto=format&fit=crop&w=1200&q=82";
const replayB="https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=1200&q=82";
const replayC="https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1200&q=82";

export default function LivePage(){return <><PublicNav/><main className="fo-live-page">
<section className="fo-live-hero"><div className="fo-live-photo" style={{backgroundImage:`linear-gradient(90deg,rgba(6,6,6,.9),rgba(6,6,6,.2)),url(${liveHero})`}}/><div className="fo-live-grid"/><div className="fo-live-copy"><span className="fo-live-badge"><Radio size={13}/> LIVE NOW · 184 MEMBERS</span><Eyebrow>Fitness Option Live</Eyebrow><h1>TRAIN<br/>WHEREVER<br/><em>YOU ARE.</em></h1><p>Join Coach Kene for a live 35-minute total-body performance session. Members can train, react, ask questions and save the replay to their week.</p><div className="fo-live-actions"><CTA href="/vanta/live/session">Join live session</CTA><CTA ghost href="#schedule">See schedule</CTA></div></div><div className="fo-live-chat"><div><b>LIVE ROOM</b><span>184 watching</span></div>{[["Amaka","That finisher 🔥"],["Chidi","Coach, alternative for knee pain?"],["Coach Kene","Use the low-impact option on screen."],["Tola","Day 12 streak completed ✅"]].map(x=><article key={x[0]+x[1]}><span>{x[0][0]}</span><p><b>{x[0]}</b>{x[1]}</p></article>)}<button><MessageCircle size={14}/> Send a message</button></div></section>
<section className="fo-live-strip"><span><Heart size={14}/> LIVE REACTIONS</span><strong>2,941</strong><span><Users size={14}/> ATTENDANCE</span><strong>184</strong><span><Clock3 size={14}/> ELAPSED</span><strong>18:42</strong><span><Video size={14}/> REPLAY</span><strong>AUTO-SAVED</strong></section>
<section className="fo-section" id="schedule"><Eyebrow>Live schedule</Eyebrow><h2 className="fo-display" style={{fontSize:"clamp(3.3rem,6.5vw,7rem)"}}>THE CLUB HAS<br/><em>A DAILY RHYTHM.</em></h2><p className="fo-copy">Morning activation, strength coaching, nutrition conversations and recovery sessions make Fitness Option useful beyond the physical gym floor.</p><div className="fo-live-schedule">{[["06:15","MORNING IGNITION","Coach Maya","Conditioning · 30 min","LIVE"],["12:30","LUNCH BREAK MOBILITY","Coach Ada","Mobility · 20 min","TODAY"],["18:30","PUSH POWER LIVE","Coach Kene","Strength · 45 min","TODAY"],["20:15","RECOVER + RESET","Coach Nneka","Recovery · 25 min","TODAY"],["SAT 09:00","ASK THE COACH","Performance Team","Q&A · 40 min","WEEKLY"]].map((x,i)=><article key={x[1]} className={i===0?"active":""}><span>{x[0]}</span><div><b>{x[1]}</b><small>{x[2]}</small></div><p>{x[3]}</p><em>{x[4]}</em><button>{i===0?"Join now":"Remind me"}</button></article>)}</div></section>
<section className="fo-section fo-replay-section"><div className="fo-replay-head"><div><Eyebrow>Replay library</Eyebrow><h2 className="fo-display" style={{fontSize:"clamp(3rem,6vw,6.5rem)"}}>MISS IT LIVE?<br/><em>DON&apos;T MISS THE WORK.</em></h2></div><Link href="/vanta/guides">Open all guides →</Link></div><div className="fo-replay-grid">{[[replayA,"ENGINE 45","38 min","Conditioning"],[replayB,"LOWER BODY LAB","52 min","Strength"],[replayC,"MOBILITY RESET","24 min","Recovery"]].map((x,i)=><article key={x[1]}><div style={{backgroundImage:`linear-gradient(0deg,rgba(5,5,5,.82),transparent),url(${x[0]})`}}><button><Play size={18}/></button><span>{x[2]}</span></div><small>{x[3]} · Replay {String(i+1).padStart(2,"0")}</small><h3>{x[1]}</h3><p>Follow-along coaching with movement options, technique cues and session notes.</p></article>)}</div></section>
<section className="v-end"><div className="v-gridfx"/><Eyebrow>Fitness Option anywhere</Eyebrow><h2>THE GYM CLOSES.<br/><em>THE COACHING DOESN&apos;T.</em></h2><p>Members can join live, catch the replay, save a session to their daily plan and keep their streak moving.</p><CTA href="/vanta/join">Join Fitness Option</CTA></section>
</main><Footer/></>}
