"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowLeft, Eye, ImagePlus, MoreHorizontal, Pencil, Plus, Search, Sparkles, UploadCloud } from "lucide-react";
import { managedListings } from "../../../lib/cms";

export default function ListingsManager(){
  const [query,setQuery]=useState("");
  const [type,setType]=useState("all");
  const items=useMemo(()=>managedListings.filter(item=>(type==="all"||item.type===type)&&`${item.title} ${item.location}`.toLowerCase().includes(query.toLowerCase())),[query,type]);
  return <main className="cms-page">
    <section className="cms-hero"><div><Link className="ops-back" href="/admin"><ArrowLeft size={15}/> Command centre</Link><p className="eyebrow">Content management</p><h1>Shortlets, properties and experiences — managed without code.</h1><p>Create listings, update rates and amenities, arrange galleries, attach video or audio, save drafts and publish when everything is ready.</p></div><Link className="cms-primary" href="#editor"><Plus size={16}/> Add new listing</Link></section>

    <section className="cms-toolbar"><div className="cms-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search listings or locations"/></div><select value={type} onChange={e=>setType(e.target.value)}><option value="all">All content</option><option value="shortlet">Shortlets</option><option value="property">Properties</option><option value="hotel">Hotels</option><option value="experience">Experiences</option></select><Link href="/admin/media"><ImagePlus size={16}/> Media library</Link></section>

    <section className="cms-table-card"><div className="cms-table-head"><span>Listing</span><span>Type</span><span>Status</span><span>Price</span><span>Updated</span><span/></div>{items.map(item=><article className="cms-table-row" key={item.id}><div className="cms-listing-cell"><div className="cms-thumb" style={{backgroundImage:`url(${item.media[0]?.url})`}}/><div><strong>{item.title}</strong><small>{item.location}</small></div></div><span className="cms-type">{item.type}</span><span className={`status-pill ${item.status}`}>{item.status}</span><strong>{item.priceLabel}</strong><span>{item.updatedAt}</span><div className="cms-row-actions"><button aria-label="Preview"><Eye size={16}/></button><button aria-label="Edit"><Pencil size={16}/></button><button aria-label="More"><MoreHorizontal size={16}/></button></div></article>)}</section>

    <section className="cms-editor" id="editor"><div className="cms-editor-copy"><p className="eyebrow dark-eye">Listing editor</p><h2>Create an exceptional stay.</h2><p>This editor is designed for the Duches team. When persistent storage is connected, these controls write directly to the live catalogue and can also prepare social campaigns from the same listing.</p><div className="cms-editor-points"><span><Sparkles size={15}/> AI description and caption assistance</span><span><UploadCloud size={15}/> Photo, video and audio media</span><span><Eye size={15}/> Preview before publishing</span></div></div><form className="listing-form" onSubmit={e=>e.preventDefault()}><div className="form-grid"><label>Listing title<input placeholder="e.g. The Azure Residence"/></label><label>Content type<select><option>Shortlet</option><option>Property for sale</option><option>Hotel / stay</option><option>Experience</option></select></label><label>Location<input placeholder="Lekki, Lagos"/></label><label>Price / rate<input placeholder="₦450,000 / night"/></label><label>Bedrooms<input type="number" placeholder="4"/></label><label>Guest capacity<input type="number" placeholder="8"/></label></div><label>Short description<textarea placeholder="Describe the residence, experience and ideal guest..."/></label><label>Amenities<input placeholder="Pool, chef, security, Wi-Fi, chauffeur..."/></label><div className="upload-drop"><UploadCloud size={28}/><strong>Drop photos, videos or audio here</strong><span>JPG, PNG, WEBP, MP4, MOV, MP3 and M4A supported after storage connection.</span><input type="file" multiple accept="image/*,video/*,audio/*"/></div><div className="publish-controls"><button type="button" className="cms-secondary">Save draft</button><button type="button" className="cms-secondary"><Sparkles size={15}/> Prepare social campaign</button><button className="cms-primary" type="submit">Publish to website</button></div></form></section>
  </main>
}
