"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Eye, ImagePlus, Loader2, Pencil, Plus, Search, Sparkles, UploadCloud } from "lucide-react";
import { managedListings } from "../../../lib/cms";

type ListingRecord={id:string;title:string;content_type?:string;type?:string;status:string;location:string;price_label?:string;priceLabel?:string;updated_at?:string;updatedAt?:string;media?:{url:string}[]};

export default function ListingsManager(){
  const [records,setRecords]=useState<ListingRecord[]>(managedListings as unknown as ListingRecord[]);
  const [query,setQuery]=useState("");const [type,setType]=useState("all");const [saving,setSaving]=useState(false);const [notice,setNotice]=useState("");
  useEffect(()=>{fetch("/api/cms/listings").then(r=>r.json()).then(d=>{if(d?.items)setRecords(d.items)}).catch(()=>{})},[]);
  const items=useMemo(()=>records.filter(item=>(type==="all"||(item.content_type??item.type)===type)&&`${item.title} ${item.location}`.toLowerCase().includes(query.toLowerCase())),[records,query,type]);
  async function save(e:React.FormEvent<HTMLFormElement>,publish:boolean){e.preventDefault();setSaving(true);setNotice("");const form=new FormData(e.currentTarget);const payload={title:form.get("title"),type:form.get("type"),location:form.get("location"),priceLabel:form.get("priceLabel"),bedrooms:Number(form.get("bedrooms")||0)||null,guestCapacity:Number(form.get("guestCapacity")||0)||null,description:form.get("description"),amenities:String(form.get("amenities")||"").split(",").map(x=>x.trim()).filter(Boolean),status:publish?"published":"draft"};const response=await fetch("/api/cms/listings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(response.ok){setNotice(data.status==="demo_only"||data.status==="persistence_not_connected"?"Saved in demo mode. Connect the production database to persist changes.":publish?"Listing published successfully.":"Draft saved successfully.");if(data.item)setRecords(current=>[data.item,...current]);e.currentTarget.reset()}else setNotice(data.error||"Unable to save listing.");setSaving(false)}
  return <main className="cms-page">
    <section className="cms-hero"><div><Link className="ops-back" href="/admin"><ArrowLeft size={15}/> Command centre</Link><p className="eyebrow">Content management</p><h1>Shortlets, properties and experiences — managed without code.</h1><p>Create listings, update rates and amenities, arrange galleries, attach media and publish when everything is ready.</p></div><Link className="cms-primary" href="#editor"><Plus size={16}/> Add new listing</Link></section>
    <section className="cms-toolbar"><div className="cms-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search listings or locations"/></div><select value={type} onChange={e=>setType(e.target.value)}><option value="all">All content</option><option value="shortlet">Shortlets</option><option value="property">Properties</option><option value="hotel">Hotels</option><option value="experience">Experiences</option></select><Link href="/admin/media"><ImagePlus size={16}/> Media library</Link></section>
    <section className="cms-table-card"><div className="cms-table-head"><span>Listing</span><span>Type</span><span>Status</span><span>Price</span><span>Updated</span><span/></div>{items.map(item=><article className="cms-table-row" key={item.id}><div className="cms-listing-cell"><div className="cms-thumb" style={item.media?.[0]?.url?{backgroundImage:`url(${item.media[0].url})`}:undefined}/><div><strong>{item.title}</strong><small>{item.location}</small></div></div><span className="cms-type">{item.content_type??item.type}</span><span className={`status-pill ${item.status}`}>{item.status}</span><strong>{item.price_label??item.priceLabel??"Contact"}</strong><span>{item.updated_at?new Date(item.updated_at).toLocaleDateString():item.updatedAt??"Today"}</span><div className="cms-row-actions"><button aria-label="Preview"><Eye size={16}/></button><button aria-label="Edit"><Pencil size={16}/></button></div></article>)}</section>
    <section className="cms-editor" id="editor"><div className="cms-editor-copy"><p className="eyebrow dark-eye">Listing editor</p><h2>Create an exceptional stay.</h2><p>These controls now submit to the Duches CMS API. With Postgres connected, new drafts and published listings persist immediately.</p><div className="cms-editor-points"><span><Sparkles size={15}/> AI-ready descriptions and captions</span><span><UploadCloud size={15}/> Reusable photo, video and audio library</span><span><Eye size={15}/> Draft before publishing</span></div></div><form className="listing-form" onSubmit={e=>save(e,true)}><div className="form-grid"><label>Listing title<input name="title" required placeholder="e.g. The Azure Residence"/></label><label>Content type<select name="type" defaultValue="shortlet"><option value="shortlet">Shortlet</option><option value="property">Property for sale</option><option value="hotel">Hotel / stay</option><option value="experience">Experience</option></select></label><label>Location<input name="location" required placeholder="Lekki, Lagos"/></label><label>Price / rate<input name="priceLabel" placeholder="₦450,000 / night"/></label><label>Bedrooms<input name="bedrooms" type="number" min="0" placeholder="4"/></label><label>Guest capacity<input name="guestCapacity" type="number" min="1" placeholder="8"/></label></div><label>Short description<textarea name="description" placeholder="Describe the residence, experience and ideal guest..."/></label><label>Amenities<input name="amenities" placeholder="Pool, chef, security, Wi-Fi, chauffeur..."/></label><Link className="upload-drop" href="/admin/media"><UploadCloud size={28}/><strong>Add photos, videos or audio in Media Library</strong><span>Upload once, then reuse assets across website listings and social campaigns.</span></Link>{notice&&<p className="cms-notice">{notice}</p>}<div className="publish-controls"><button type="button" className="cms-secondary" disabled={saving} onClick={e=>{const form=e.currentTarget.form;if(form)save({preventDefault:()=>{},currentTarget:form} as unknown as React.FormEvent<HTMLFormElement>,false)}}>Save draft</button><Link href="/admin/content" className="cms-secondary"><Sparkles size={15}/> Prepare social campaign</Link><button className="cms-primary" type="submit" disabled={saving}>{saving?<><Loader2 size={15}/> Saving…</>:"Publish to website"}</button></div></form></section>
  </main>
}
