import Link from "next/link";
import { CalendarDays, Check, Clock3, Droplets, Flame, HeartPulse, Moon, Play, Sparkles, Utensils } from "lucide-react";
import { CTA, Eyebrow, Footer, PublicNav } from "../ui";

export default function DailyPlanPage(){const tasks=[["07:00","Hydrate + morning check-in","500ml water · energy + soreness","done"],["08:15","Protein-first breakfast","38g protein · 610 kcal","done"],["12:30","8-minute mobility reset","Hips · thoracic spine · ankles","now"],["18:30","Push Power · Week 7","52 min · strength emphasis","next"],["20:15","Live Recover + Reset","25 min · Coach Nneka","live"],["22:45","Sleep target","8h 10m target","sleep"]];return <><PublicNav/><main className="fo-daily-page">
<section className="fo-daily-hero"><div><Eyebrow>Fitness Option · Today</Eyebrow><h1 className="fo-display">ONE DAY.<br/><em>FULLY DIRECTED.</em></h1><p className="fo-copy">The member should never wonder what matters today. Training, nutrition, hydration, recovery and live coaching sit inside one adaptive rhythm.</p><div className="fo-social-proof"><span><Sparkles size={13}/> Readiness 86</span><span><Flame size={13}/> 9 day streak</span><span><CalendarDays size={13}/> Week 7</span></div></div><div className="fo-day-score"><span>WED · SEP 02</span><strong>86</strong><small>READINESS</small><p>High recovery. Keep planned strength volume; use the shoulder-friendly press variation.</p></div></section>
<section className="fo-section" style={{paddingTop:"2rem"}}><div className="fo-day-layout"><div className="fo-day-timeline"><Eyebrow>Your day</Eyebrow>{tasks.map((x,i)=><article className={x[3]} key={x[1]}><div className="fo-time"><span>{x[0]}</span><i/></div><div><b>{x[1]}</b><small>{x[2]}</small></div><button>{x[3]==="done"?<Check size={14}/>:x[3]==="live"?<Play size={14}/>:<Clock3 size={14}/>}</button></article>)}</div><aside className="fo-day-side"><article className="fo-day-coach"><span><Sparkles size={15}/> FITNESS OPTION COACH AI</span><h3>Today changed for a reason.</h3><p>Your recovery score supports the planned workload, but shoulder soreness moved overhead pressing out. Landmine press stays in because it preserves the training goal with a friendlier position.</p><Link href="/vanta/form-check">Review movement context →</Link></article><article><span><Droplets/> HYDRATION</span><strong>2.4<small>/3.2L</small></strong><i><em style={{width:"75%"}}/></i><p>800ml remaining before sleep.</p></article><article><span><Utensils/> NUTRITION</span><strong>2,110<small>/2,650 kcal</small></strong><i><em style={{width:"80%"}}/></i><p>Protein 151g · target 175g.</p></article><article><span><Moon/> RECOVERY</span><strong>8h10<small> target</small></strong><p>Wind-down reminder at 22:15.</p></article></aside></div></section>
<section className="fo-section fo-daily-workout"><div><Eyebrow>Main session</Eyebrow><h2 className="fo-display" style={{fontSize:"clamp(3rem,6vw,6.5rem)"}}>PUSH<br/><em>POWER.</em></h2><p className="fo-copy">Four movements, precise targets, technique links and the option to launch a Form Check from supported exercises.</p><CTA href="/vanta/app">Open workout</CTA></div><div className="fo-exercise-stack">{[["01","Incline DB Press","4 × 8","32.5kg"],["02","Cable Fly","3 × 12","17.5kg"],["03","Landmine Press","3 × 10","25kg"],["04","Rope Extension","3 × 15","27.5kg"]].map((x,i)=><article key={x[0]}><span>{x[0]}</span><div><b>{x[1]}</b><small>{x[2]}</small></div><strong>{x[3]}</strong><Link href={i===2?"/vanta/form-check":"/vanta/guides"}>{i===2?"Form Check":"Guide"} →</Link></article>)}</div></section>
<section className="fo-section"><Eyebrow>Daily intelligence</Eyebrow><div className="fo-education-grid"><article><HeartPulse/><h3>Recovery-aware</h3><p>Sleep, soreness, session history and feedback can shape the next recommendation.</p></article><article><Utensils/><h3>Nutrition-aware</h3><p>Daily macro and hydration targets live beside the training plan rather than in a separate disconnected app.</p></article><article><Play/><h3>Live-aware</h3><p>Relevant live classes and replays can drop directly into the member&apos;s day.</p></article></div></section>
<section className="v-end"><div className="v-gridfx"/><Eyebrow>Come back tomorrow</Eyebrow><h2>THE APP HAS<br/><em>A REASON TO OPEN DAILY.</em></h2><p>That daily rhythm is what turns Fitness Option from a membership card into a coaching relationship.</p><CTA href="/vanta/live">See Fitness Option Live</CTA></section>
</main><Footer/></>}
